import type {} from '../../typedef';
export const domQuery: {
	getPositionIndex: typeof import('./domQuery').getPositionIndex;
	getNodePath: typeof import('./domQuery').getNodePath;
	getNodeFromPath: typeof import('./domQuery').getNodeFromPath;
	getChildNode: typeof import('./domQuery').getChildNode;
	getListChildren: typeof import('./domQuery').getListChildren;
	getListChildNodes: typeof import('./domQuery').getListChildNodes;
	getNodeDepth: typeof import('./domQuery').getNodeDepth;
	sortNodeByDepth: typeof import('./domQuery').sortNodeByDepth;
	compareElements: typeof import('./domQuery').compareElements;
	getParentElement: typeof import('./domQuery').getParentElement;
	getParentElements: typeof import('./domQuery').getParentElements;
	getCommandTarget: typeof import('./domQuery').getCommandTarget;
	getEventTarget: typeof import('./domQuery').getEventTarget;
	getEdgeChild: typeof import('./domQuery').getEdgeChild;
	getEdgeChildNodes: typeof import('./domQuery').getEdgeChildNodes;
	getPreviousDeepestNode: typeof import('./domQuery').getPreviousDeepestNode;
	getNextDeepestNode: typeof import('./domQuery').getNextDeepestNode;
	findTextIndexOnLine: typeof import('./domQuery').findTextIndexOnLine;
	findTabEndIndex: typeof import('./domQuery').findTabEndIndex;
	findVisualLastCell: typeof import('./domQuery').findVisualLastCell;
	getScrollParents: typeof import('./domQuery').getScrollParents;
	getIframeDocument: typeof import('./domQuery').getIframeDocument;
};
export const domCheck: {
	isZeroWidth: typeof import('./domCheck').isZeroWidth;
	isEdgePoint: typeof import('./domCheck').isEdgePoint;
	isText: typeof import('./domCheck').isText;
	isElement: typeof import('./domCheck').isElement;
	isInputElement: typeof import('./domCheck').isInputElement;
	isButtonElement: typeof import('./domCheck').isButtonElement;
	isList: typeof import('./domCheck').isList;
	isListCell: typeof import('./domCheck').isListCell;
	isTable: typeof import('./domCheck').isTable;
	isTableElements: typeof import('./domCheck').isTableElements;
	isTableCell: typeof import('./domCheck').isTableCell;
	isTableRow: typeof import('./domCheck').isTableRow;
	isBreak: typeof import('./domCheck').isBreak;
	isAnchor: typeof import('./domCheck').isAnchor;
	isMedia: typeof import('./domCheck').isMedia;
	isIFrame: typeof import('./domCheck').isIFrame;
	isFigure: typeof import('./domCheck').isFigure;
	isContentLess: typeof import('./domCheck').isContentLess;
	isEmptyLine: typeof import('./domCheck').isEmptyLine;
	isComponentContainer: typeof import('./domCheck').isComponentContainer;
	isWysiwygFrame: typeof import('./domCheck').isWysiwygFrame;
	isNonEditable: typeof import('./domCheck').isNonEditable;
	isSpanWithoutAttr: typeof import('./domCheck').isSpanWithoutAttr;
	isSameAttributes: typeof import('./domCheck').isSameAttributes;
	isExcludeFormat: typeof import('./domCheck').isExcludeFormat;
	isUneditable: typeof import('./domCheck').isUneditable;
	isImportantDisabled: typeof import('./domCheck').isImportantDisabled;
};
export const domUtils: {
	clone: typeof import('./domUtils').clone;
	createElement: typeof import('./domUtils').createElement;
	createTextNode: typeof import('./domUtils').createTextNode;
	getAttributesToString: typeof import('./domUtils').getAttributesToString;
	arrayFilter: typeof import('./domUtils').arrayFilter;
	arrayFind: typeof import('./domUtils').arrayFind;
	arrayIncludes: typeof import('./domUtils').arrayIncludes;
	getArrayIndex: typeof import('./domUtils').getArrayIndex;
	nextIndex: typeof import('./domUtils').nextIndex;
	prevIndex: typeof import('./domUtils').prevIndex;
	copyTagAttributes: typeof import('./domUtils').copyTagAttributes;
	copyFormatAttributes: typeof import('./domUtils').copyFormatAttributes;
	removeItem: typeof import('./domUtils').removeItem;
	changeElement: typeof import('./domUtils').changeElement;
	changeTxt: typeof import('./domUtils').changeTxt;
	setStyle: typeof import('./domUtils').setStyle;
	getStyle: typeof import('./domUtils').getStyle;
	setDisabled: typeof import('./domUtils').setDisabled;
	hasClass: typeof import('./domUtils').hasClass;
	addClass: typeof import('./domUtils').addClass;
	removeClass: typeof import('./domUtils').removeClass;
	toggleClass: typeof import('./domUtils').toggleClass;
	flashClass: typeof import('./domUtils').flashClass;
	getClientSize: typeof import('./domUtils').getClientSize;
	getViewportSize: typeof import('./domUtils').getViewportSize;
	applyInlineStylesAll: typeof import('./domUtils').applyInlineStylesAll;
	waitForMediaLoad: typeof import('./domUtils').waitForMediaLoad;
	getRootCssVar: typeof import('./domUtils').getRootCssVar;
	setRootCssVar: typeof import('./domUtils').setRootCssVar;
	createTooltipInner: typeof import('./domUtils').createTooltipInner;
};
export default dom;
declare namespace dom {
	export { query };
	export { check };
	export { utils };
}
import check from './domCheck';
import query from './domQuery';
import utils from './domUtils';
