/**
 * @version 1.0.0
 * Global Type Declarations for SunEditor Custom Types
 *
 * This file contains the global type declarations that were generated by copying
 * the contents of the built typedef.d.ts file (originally generated from typedef.js)
 * into a global declaration block. The original typedef.d.ts file has been removed
 * to prevent duplicate type definitions.
 *
 * These types are now available globally throughout the project without requiring
 * explicit imports. For management purposes, typedef.js includes version information.
 * Each time you update these types by copying and pasting, please ensure that the
 * version in this file is synchronized with the version specified in typedef.js.
 *
 * Version: <insert_version_here>
 */

export {};

declare global {
	type NodeCollection = Array<Node> | HTMLCollection | NodeList;
	type EditorCore = import('./core/editor').default;
	type EditorInjector = import('./editorInjector').default;
	type CoreInjector = import('./editorInjector/_core').default;
	type EditorStatus = {
		/**
		 * Boolean value of whether the editor has focus
		 */
		hasFocus: boolean;
		/**
		 * Indent size of tab (4)
		 */
		tabSize: number;
		/**
		 * Indent size (25)px
		 */
		indentSize: number;
		/**
		 * Indent size of Code view mode (2)
		 */
		codeIndentSize: number;
		/**
		 * An element array of the current cursor's node structure
		 */
		currentNodes: Array<string>;
		/**
		 * An element name array of the current cursor's node structure
		 */
		currentNodesMap: Array<string>;
		/**
		 * Boolean value of whether component is selected
		 */
		onSelected: boolean;
		/**
		 * Current root key
		 */
		rootKey: number;
		/**
		 * Current range object
		 */
		_range: Range;
		/**
		 * Mouse down event status
		 */
		_onMousedown: boolean;
	};
	type EventInfo = {
		/**
		 * Target element
		 */
		target: any;
		/**
		 * Event type
		 */
		type: string;
		/**
		 * Event listener
		 */
		listener: (...args: any) => any;
		/**
		 * Event useCapture option
		 */
		useCapture?: (boolean | AddEventListenerOptions) | undefined;
	};
	type GlobalEventInfo = {
		/**
		 * Event type
		 */
		type: string;
		/**
		 * Event listener
		 */
		listener: (...args: any) => any;
		/**
		 * Use event capture
		 */
		useCapture?: (boolean | AddEventListenerOptions) | undefined;
	};
	type PluginMouseEventInfo = {
		/**
		 * Frame context
		 */
		frameContext: FrameContext;
		/**
		 * Event object
		 */
		event: MouseEvent;
	};
	type PluginKeyEventInfo = {
		/**
		 * Frame context
		 */
		frameContext: FrameContext;
		/**
		 * Event object
		 */
		event: KeyboardEvent;
		/**
		 * range object
		 */
		range: Range;
		/**
		 * Current line element
		 */
		line: HTMLElement;
	};
	type PluginToolbarInputChangeEventInfo = {
		/**
		 * Input element
		 */
		target: HTMLElement;
		/**
		 * Event object
		 */
		event: Event;
		/**
		 * Input value
		 */
		value: string;
	};
	type EditorFrameOptions = {
		/**
		 * - Initial value for the editor.
		 */
		value?: string;
		/**
		 * - Placeholder text.
		 */
		placeholder?: string;
		/**
		 * - Attributes for the editable frame[.sun-editor-editable]. (e.g. [key]: value)
		 */
		editableFrameAttributes?: {
			[x: string]: string;
		};
		/**
		 * - Width for the editor.
		 */
		width?: string;
		/**
		 * - Min width for the editor.
		 */
		minWidth?: string;
		/**
		 * - Max width for the editor.
		 */
		maxWidth?: string;
		/**
		 * - Height for the editor.
		 */
		height?: string;
		/**
		 * - Min height for the editor.
		 */
		minHeight?: string;
		/**
		 * - Max height for the editor.
		 */
		maxHeight?: string;
		/**
		 * - Style string of the top frame of the editor. (e.g. "border: 1px solid #ccc;").
		 */
		editorStyle?: string;
		/**
		 * - Content will be placed in an iframe and isolated from the rest of the page.
		 */
		iframe?: boolean;
		/**
		 * - Allows the usage of HTML, HEAD, BODY tags and DOCTYPE declaration on the "iframe".
		 */
		iframe_fullPage?: boolean;
		/**
		 * - Attributes of the "iframe". (e.g. {'scrolling': 'no'})
		 */
		iframe_attributes?: {
			[x: string]: string;
		};
		/**
		 * - Name or Array of the CSS file to apply inside the iframe.
		 * - You can also use regular expressions.
		 * - Applied by searching by filename in the link tag of document,
		 * - or put the URL value (".css" can be omitted).
		 */
		iframe_cssFileName?: string;
		/**
		 * - Enables the status bar.
		 */
		statusbar?: boolean;
		/**
		 * - Displays the current node structure to status bar.
		 */
		statusbar_showPathLabel?: boolean;
		/**
		 * - Enables resize function of bottom status bar
		 */
		statusbar_resizeEnable?: boolean;
		/**
		 * - Shows the number of characters in the editor.
		 * - If the maxCharCount option has a value, it becomes true.
		 */
		charCounter?: boolean;
		/**
		 * - The maximum number of characters allowed to be inserted into the editor.
		 */
		charCounter_max?: number;
		/**
		 * - Text to be displayed in the "charCounter" area of the bottom bar. (e.g. "Characters : 20/200")
		 */
		charCounter_label?: string;
		/**
		 * - Defines the calculation method of the "charCounter" option.
		 * - 'char': Characters length.
		 * - 'byte': Binary data size of characters.
		 * - 'byte-html': Binary data size of the full HTML string.
		 */
		charCounter_type?: 'char' | 'byte' | 'byte-html';
	};
	type EditorBaseOptions = {
		/**
		 * - Plugin configuration.
		 */
		plugins?:
			| {
					[x: string]: any;
			  }
			| Array<{
					[x: string]: any;
			  }>;
		/**
		 * - Plugin configuration.
		 */
		excludedPlugins?: Array<string>;
		/**
		 * - List of toolbar buttons, grouped by sub-arrays.
		 */
		buttonList?: Array<string[] | string>;
		/**
		 * - Enables migration mode for SunEditor v2.
		 */
		v2Migration?: boolean;
		/**
		 * - Enables strict filtering of tags, attributes, and styles.
		 */
		strictMode?:
			| boolean
			| {
					tagFilter: boolean;
					formatFilter: boolean;
					classFilter: boolean;
					styleNodeFilter: boolean;
					attrFilter: boolean;
					styleFilter: boolean;
			  };
		/**
		 * - Toolbar mode: "classic", "inline", "balloon", "balloon-always".
		 */
		mode?: 'classic' | 'inline' | 'balloon' | 'balloon-always';
		/**
		 * - Editor type: "document:header,page".
		 */
		type?: string;
		/**
		 * - Editor theme.
		 */
		theme?: string;
		/**
		 * - Language configuration.
		 */
		lang?: {
			[x: string]: string;
		};
		/**
		 * - Allowed font size units.
		 */
		fontSizeUnits?: Array<string>;
		/**
		 * - Allowed class names.
		 */
		allowedClassName?: string;
		/**
		 * - Closes modals when clicking outside.
		 */
		closeModalOutsideClick?: boolean;
		/**
		 * - Keeps the format of the copied content.
		 */
		copyFormatKeepOn?: boolean;
		/**
		 * - Synchronizes tab indent with spaces.
		 */
		syncTabIndent?: boolean;
		/**
		 * - Disables tab key input.
		 */
		tabDisable?: boolean;
		/**
		 * - Automatically converts URLs into hyperlinks. ("Link" plugin required)
		 */
		autoLinkify?: boolean;
		/**
		 * - Styles applied automatically on text input.
		 */
		autoStyleify?: Array<string>;
		/**
		 * - Configuration for scroll behavior when navigating editor content.
		 */
		scrollToOptions?: {
			[x: string]: string | number;
		};
		/**
		 * - Configuration for scroll behavior when navigating components.
		 */
		componentScrollToOptions?: {
			[x: string]: string | number;
		};
		/**
		 * - This option determines how inline elements (such as <span>, <strong>, etc.) are handled when deleting text.
		 * - "repeat": Inline styles are retained unless the backspace key is repeatedly pressed. If the user continuously presses backspace, the styles will eventually be removed.
		 * - "none": Inline styles are not retained at all. When deleting text, the associated inline elements are immediately removed along with it.
		 * - "always": Inline styles persist indefinitely unless explicitly removed. Even if all text inside an inline element is deleted, the element itself remains until manually removed.
		 */
		retainStyleMode?: 'repeat' | 'always' | 'none';
		/**
		 * - Specifies extra allowed or disallowed tags.
		 */
		allowedExtraTags?: {
			[x: string]: boolean;
		};
		/**
		 * - Custom event handlers.
		 */
		events?: {
			[x: string]: (...args: any) => any;
		};
		/**
		 * - The basic tags that serves as the base for "textStyleTags"
		 */
		__textStyleTags?: string;
		/**
		 * - Additional text style tags.
		 */
		textStyleTags?: string;
		/**
		 * - Maps text styles to specific HTML tags.
		 */
		convertTextTags?: {
			[x: string]: string;
		};
		/**
		 * - The basic tags that serves as the base for "tagStyles"
		 */
		__tagStyles?: {
			[x: string]: string;
		};
		/**
		 * - Specifies allowed styles for HTML tags.
		 */
		tagStyles?: {
			[x: string]: string;
		};
		/**
		 * - Specifies allowed styles for the "span" tag.
		 */
		spanStyles?: string;
		/**
		 * - Specifies allowed styles for the "line" element (p..).
		 */
		lineStyles?: string;
		/**
		 * - Text direction: "ltr" or "rtl".
		 */
		textDirection?: string;
		/**
		 * - An array of command pairs whose shortcut icons should be opposite each other, depending on the "textDirection" mode.
		 */
		reverseButtons?: Array<string>;
		/**
		 * - Delay time for history stack updates (ms).
		 */
		historyStackDelayTime?: number;
		/**
		 * - Line properties that should be reset when changing lines (e.g. "id|name").
		 */
		lineAttrReset?: string;
		/**
		 * - Class name for printing.
		 */
		printClass?: string;
		/**
		 * - Default line element when inserting new lines.
		 */
		defaultLine?: string;
		/**
		 * - Default allowed HTML elements. The default values are maintained.
		 */
		__defaultElementWhitelist?: string;
		/**
		 * - Allowed HTML elements. Delimiter: "|" (e.g. "p|div", "*").
		 */
		elementWhitelist?: string;
		/**
		 * - Disallowed HTML elements. Delimiter: "|" (e.g. "script|style").
		 */
		elementBlacklist?: string;
		/**
		 * - Allowed attributes. Delimiter: "|" (e.g. "href|target").
		 */
		__defaultAttributeWhitelist?: string;
		/**
		 * - Allowed attributes. (e.g. {a: "href|target", img: "src|alt"}).
		 */
		attributeWhitelist?: {
			[x: string]: string;
		};
		/**
		 * - Disallowed attributes. (e.g. {a: "href|target", img: "src|alt"}).
		 */
		attributeBlacklist?: {
			[x: string]: string;
		};
		/**
		 * - Overrides the editor's default "line" element.
		 */
		__defaultFormatLine?: string;
		/**
		 * - Specifies the editor's "line" elements.
		 * - (P, DIV, H[1-6], PRE, LI | class="__se__format__line_xxx")
		 * - "line" element also contain "brLine" element
		 */
		formatLine?: string;
		/**
		 * - Overrides the editor's default "brLine" element.
		 */
		__defaultFormatBrLine?: string;
		/**
		 * - Specifies the editor's "brLine" elements. (e.g. "PRE").
		 * - (PRE | class="__se__format__br_line_xxx")
		 * - "brLine" elements is included in the "line" element.
		 * - "brLine" elements's line break is "BR" tag.
		 * ※ Entering the Enter key in the space on the last line ends "brLine" and appends "line".
		 */
		formatBrLine?: string;
		/**
		 * - Overrides the editor's default "closureBrLine" element.
		 */
		__defaultFormatClosureBrLine?: string;
		/**
		 * - Specifies the editor's "closureBrLine" elements.
		 * - (class="__se__format__br_line__closure_xxx")
		 * - "closureBrLine" elements is included in the "brLine".
		 * - "closureBrLine" elements's line break is "BR" tag.
		 * - ※ You cannot exit this format with the Enter key or Backspace key.
		 * - ※ Use it only in special cases. ([ex] format of table cells)
		 */
		formatClosureBrLine?: string;
		/**
		 * - Overrides the editor's default "block" element.
		 */
		__defaultFormatBlock?: string;
		/**
		 * - Specifies the editor's "block" elements.
		 * - (BLOCKQUOTE, OL, UL, FIGCAPTION, TABLE, THEAD, TBODY, TR, TH, TD | class="__se__format__block_xxx")
		 * - "block" is wrap the "line" and "component"
		 */
		formatBlock?: string;
		/**
		 * - Overrides the editor's default "closureBlock" element.
		 */
		__defaultFormatClosureBlock?: string;
		/**
		 * - Specifies the editor's "closureBlock" elements.
		 * - (TH, TD | class="__se__format__block_closure_xxx")
		 * - "closureBlock" elements is included in the "block".
		 * - "closureBlock" element is wrap the "line" and "component"
		 * - ※ You cannot exit this format with the Enter key or Backspace key.
		 * - ※ Use it only in special cases. ([ex] format of table cells)
		 */
		formatClosureBlock?: string;
		/**
		 * - Allowed empty tags.
		 */
		allowedEmptyTags?: string;
		/**
		 * - Toolbar width.
		 */
		toolbar_width?: number | string;
		/**
		 * - Container element for the toolbar.
		 */
		toolbar_container?: Element | string;
		/**
		 * - Enables sticky toolbar with optional offset.
		 */
		toolbar_sticky?: number;
		/**
		 * - Hides toolbar initially.
		 */
		toolbar_hide?: boolean;
		/**
		 * - Sub-toolbar configuration.
		 */
		subToolbar?: {
			buttonList?: Array<Array<string>>;
			mode?: 'balloon' | 'balloon-always';
			width?: number | string;
		};
		/**
		 * - Container element for the status bar.
		 */
		statusbar_container?: Element | string;
		/**
		 * - Displays shortcut hints in tooltips.
		 */
		shortcutsHint?: boolean;
		/**
		 * - Disables keyboard shortcuts.
		 */
		shortcutsDisable?: boolean;
		/**
		 * - Custom keyboard shortcuts.
		 */
		shortcuts?: {
			[x: string]: string[];
		};
		/**
		 * - Offset applied when entering fullscreen mode.
		 */
		fullScreenOffset?: number;
		/**
		 * - Custom template for preview mode.
		 */
		previewTemplate?: string;
		/**
		 * - Custom template for print mode.
		 */
		printTemplate?: string;
		/**
		 * - Enables automatic selection of inserted components.
		 */
		componentAutoSelect?: boolean;
		/**
		 * - Default URL protocol for links.
		 */
		defaultUrlProtocol?: string;
		/**
		 * - Specifies additional styles to the list of allowed styles. Delimiter: "|" (e.g. "color|background-color").
		 */
		allUsedStyles?: string;
		/**
		 * - Overrides the default icons.
		 */
		icons?: {
			[x: string]: string;
		};
		/**
		 * - Enables free code view mode.
		 */
		freeCodeViewMode?: string;
		/**
		 * - Line format filter configuration.
		 */
		__lineFormatFilter?: boolean;
		/**
		 * - Plugin retain filter configuration.
		 */
		__pluginRetainFilter?: boolean;
		/**
		 * - Defines the list of styles that are applied directly to the `<li>` element
		 * - when a text style is applied to the entire list item.
		 * - For example, when changing the font size or color of a list item (`<li>`),
		 * - these styles will be applied to the `<li>` tag instead of wrapping the content inside additional tags.
		 */
		__listCommonStyle?: Array<string>;
		/**
		 * - External libraries like CodeMirror or MathJax.
		 */
		externalLibs?: {
			[x: string]: any;
		};
		/**
		 * - Dynamic plugin options, where the key is the plugin name and the value is its configuration.
		 */
		PluginOptions?: {
			[x: string]: any;
		};
	};
	type FrameOptions = Map<string, any>;
	type FrameContext = Map<string, any>;
	type Context = Map<string, any>;
}
