/**
 * @version 1.0.0
 * Global Type Declarations for SunEditor Custom Types
 *
 * This file contains the global type declarations that were generated by copying
 * the contents of the built typedef.d.ts file (originally generated from typedef.js)
 * into a global declaration block. The original typedef.d.ts file has been removed
 * to prevent duplicate type definitions.
 *
 * These types are now available globally throughout the project without requiring
 * explicit imports. For management purposes, typedef.js includes version information.
 * Each time you update these types by copying and pasting, please ensure that the
 * version in this file is synchronized with the version specified in typedef.js.
 *
 * Version: <insert_version_here>
 */

export {};

declare global {
	type __se__NodeCollection = Array<Node> | HTMLCollection | NodeList;
	type __se__EditorCore = import('./core/editor').default;
	type __se__EditorInjector = import('./editorInjector').default;
	type __se__CoreInjector = import('./editorInjector/_core').default;
	type __se__EditorStatus = {
		/**
		 * Boolean value of whether the editor has focus
		 */
		hasFocus: boolean;
		/**
		 * Indent size of tab (4)
		 */
		tabSize: number;
		/**
		 * Indent size (25)px
		 */
		indentSize: number;
		/**
		 * Indent size of Code view mode (2)
		 */
		codeIndentSize: number;
		/**
		 * An element array of the current cursor's node structure
		 */
		currentNodes: Array<string>;
		/**
		 * An element name array of the current cursor's node structure
		 */
		currentNodesMap: Array<string>;
		/**
		 * Boolean value of whether component is selected
		 */
		onSelected: boolean;
		/**
		 * Current root key
		 */
		rootKey: number;
		/**
		 * Current range object
		 */
		_range: Range;
		/**
		 * Mouse down event status
		 */
		_onMousedown: boolean;
	};
	type __se__EventInfo = {
		/**
		 * Target element
		 */
		target: any;
		/**
		 * Event type
		 */
		type: string;
		/**
		 * Event listener
		 */
		listener: (...args: any) => any;
		/**
		 * Event useCapture option
		 */
		useCapture?: (boolean | AddEventListenerOptions) | undefined;
	};
	type __se__GlobalEventInfo = {
		/**
		 * Event type
		 */
		type: string;
		/**
		 * Event listener
		 */
		listener: (...args: any) => any;
		/**
		 * Use event capture
		 */
		useCapture?: (boolean | AddEventListenerOptions) | undefined;
	};
	type __se__PluginMouseEventInfo = {
		/**
		 * Frame context
		 */
		frameContext: __se__FrameContext;
		/**
		 * Event object
		 */
		event: MouseEvent;
	};
	type __se__PluginKeyEventInfo = {
		/**
		 * Frame context
		 */
		frameContext: __se__FrameContext;
		/**
		 * Event object
		 */
		event: KeyboardEvent;
		/**
		 * range object
		 */
		range: Range;
		/**
		 * Current line element
		 */
		line: HTMLElement;
	};
	type __se__PluginToolbarInputChangeEventInfo = {
		/**
		 * Input element
		 */
		target: HTMLElement;
		/**
		 * Event object
		 */
		event: Event;
		/**
		 * Input value
		 */
		value: string;
	};
	type __se__FrameOptions = Map<string, any>;
	type __se__FrameContext = Map<string, any>;
	type __se__Context = Map<string, any>;
}
