// Czechoslovakia
(function (global, factory) {
	if (typeof module === 'object' && typeof module.exports === 'object') {
		module.exports = global.document
			? factory(global, true)
			: function (w) {
					if (!w.document) {
						throw new Error('SUNEDITOR_LANG a window with a document');
					}
					return factory(w);
			  };
	} else {
		factory(global);
	}
})(typeof window !== 'undefined' ? window : this, function (window, noGlobal) {
	const lang = {
		code: 'cs',
		align: 'Zarovnat',
		alignBottom: 'Zarovnejte spodní část',
		alignCenter: 'Zarovnat na střed',
		alignJustify: 'Zarovnat do bloku',
		alignLeft: 'Zarovnat vlevo',
		alignMiddle: 'Zarovnejte střed',
		alignRight: 'Zarovnat vpravo',
		alignTop: 'Zarovnejte horní část',
		anchor: 'Kotva',
		asBlock: 'Jako blok',
		asInline: 'Jako inline',
		asLink: 'Jako odkaz',
		audio: 'Zvuk',
		audioGallery: 'Audiogalerie',
		audio_modal_file: 'Vybrat ze souborů',
		audio_modal_title: 'Vložit zvuk',
		audio_modal_url: 'Adresa URL zvuku',
		autoSize: 'Automatická velikost',
		backgroundColor: 'Barva zvýraznění',
		basic: 'Základní',
		blockStyle: 'Blokový styl',
		bold: 'Tučné',
		border: 'Pohraniční',
		border_all: 'Ohraničit vše',
		border_inside: 'Hranice uvnitř',
		border_horizontal: 'Hranice horizontální',
		border_vertical: 'Vertikální hranice',
		border_outside: 'Hranice venku',
		border_left: 'Hranice vlevo',
		border_top: 'Horní okraj',
		border_right: 'Ohraničení vpravo',
		border_bottom: 'Hraniční dno',
		border_none: 'Hranice žádná',
		bulletedList: 'Neřazený seznam',
		cancel: 'Zrušit',
		caption: 'Vložit popis',
		cellProperties: 'Vlastnosti buněk',
		center: 'Střed',
		close: 'Zavřít',
		codeView: 'Zobrazení kódu',
		color: 'Barva',
		colorPicker: 'Výběr barvy',
		column: 'Sloupec',
		comment: 'Komentáře',
		commentAdd: 'Přidat komentář',
		commentShow: 'Zobrazit komentáře',
		copy: 'Kopie',
		copyFormat: 'Formátování barvy',
		cut: 'Střih',
		default: 'Výchozí',
		deleteColumn: 'Smazat sloupec',
		deleteRow: 'Smazat řádek',
		dir_ltr: 'Zleva doprava',
		dir_rtl: 'Zprava doleva',
		download: 'Stáhnout',
		drag: 'Táhnout',
		drawing: 'Výkres',
		drawing_modal_title: 'Výkres',
		edit: 'Upravit',
		embed: 'Vložit',
		embed_modal_title: 'Vložit',
		embed_modal_source: 'Vložit zdroj / URL',
		exportPDF: 'Export do PDF',
		exportWord: 'Export do Word',
		find: 'Nalézt',
		decrease: 'Pokles',
		increase: 'Zvýšení',
		fileBrowser: 'Prohlížeč souborů',
		fileGallery: 'Galerie souborů',
		fileUpload: 'Nahrání souboru',
		fixedColumnWidth: 'Pevná šířka sloupce',
		font: 'Písmo',
		fontColor: 'Barva písma',
		fontSize: 'Velikost',
		formats: 'Formáty',
		fullScreen: 'Celá obrazovka',
		height: 'Výška',
		horizontalLine: 'Vodorovná čára',
		horizontalSplit: 'Vodorovné rozdělení',
		hr_dashed: 'Čárkovaná',
		hr_dotted: 'Tečkovaná',
		hr_solid: 'Nepřerušovaná',
		id: 'ID',
		image: 'Obrázek',
		imageGallery: 'Obrázková galerie',
		image_modal_altText: 'Alternativní text',
		image_modal_file: 'Vybrat ze souborů',
		image_modal_title: 'Vložit obrázek',
		image_modal_url: 'URL obrázku',
		importWord: 'Import z Wordu',
		indent: 'Odsadit',
		inlineStyle: 'Inline styl',
		insertColumnAfter: 'Vložit sloupec za',
		insertColumnBefore: 'Vložit sloupec před',
		insertRowAbove: 'Vložit řádek výše',
		insertRowBelow: 'Vložit řádek níže',
		insertLine: 'Vložit řádek',
		italic: 'Kurzíva',
		layout: 'Rozložení',
		left: 'Vlevo',
		lineHeight: 'Výška řádku',
		link: 'Odkaz',
		link_modal_bookmark: 'Záložka',
		link_modal_downloadLinkCheck: 'Odkaz ke stažení',
		link_modal_newWindowCheck: 'Otevřít v novém okně',
		link_modal_text: 'Text k zobrazení',
		link_modal_title: 'Vložit odkaz',
		link_modal_url: 'URL pro odkaz',
		link_modal_relAttribute: 'Atribut Rel',
		list: 'Seznam',
		math: 'Matematika',
		math_modal_fontSizeLabel: 'Velikost písma',
		math_modal_inputLabel: 'Matematická notace',
		math_modal_previewLabel: 'Náhled',
		math_modal_title: 'Matematika',
		maxSize: 'Max. velikost',
		mediaGallery: 'Galerie médií',
		mention: 'Zmínka',
		menu_bordered: 'Ohraničené',
		menu_code: 'Kód',
		menu_neon: 'Neon',
		menu_shadow: 'Stín',
		menu_spaced: 'Rozložené',
		menu_translucent: 'Průsvitné',
		mergeCells: 'Spojit buňky',
		minSize: 'Min. velikost',
		mirrorHorizontal: 'Zrcadlo, horizontální',
		mirrorVertical: 'Zrcadlo, vertikální',
		newDocument: 'Nový dokument',
		numberedList: 'Seřazený seznam',
		outdent: 'Předsadit',
		pageBreak: 'Konec stránky',
		pageDown: 'O stránku dolů',
		pageNumber: 'Číslo stránky',
		pageUp: 'O stránku nahoru',
		paragraphStyle: 'Styl odstavce',
		preview: 'Náhled',
		print: 'tisk',
		proportion: 'Omezení proporcí',
		ratio: 'Poměr',
		redo: 'Opakovat',
		remove: 'Odebrat',
		removeFormat: 'Odebrat formát',
		replace: 'Nahradit',
		replaceAll: 'Vyměňte všechny',
		resize100: 'Změnit velikost 100%',
		resize25: 'Změnit velikost 25%',
		resize50: 'Změnit velikost 50%',
		resize75: 'Změnit velikost 75%',
		resize: 'Změnit velikost',
		revert: 'Vrátit zpět',
		revisionHistory: 'Historie revizí',
		right: 'Vpravo',
		rotateLeft: 'Otočit doleva',
		rotateRight: 'Otočit doprava',
		row: 'Řádek',
		save: 'Uložit',
		search: 'Hledat',
		selectAll: 'Vyberte Vše',
		showBlocks: 'Zobrazit bloky',
		size: 'Velikost',
		splitCells: 'Rozdělit buňky',
		strike: 'Přeškrtnutí',
		submitButton: 'Odeslat',
		subscript: 'Dolní index',
		superscript: 'Horní index',
		table: 'Tabulka',
		tableHeader: 'Záhlaví tabulky',
		tableProperties: 'Vlastnosti tabulky',
		tags: 'Štítky',
		tag_blockquote: 'Citovat',
		tag_div: 'Normální (DIV)',
		tag_h: 'Záhlaví',
		tag_p: 'Odstavec',
		tag_pre: 'Kód',
		template: 'Šablona',
		textStyle: 'Styl textu',
		title: 'Titul',
		underline: 'Podtržení',
		undo: 'Zpět',
		unlink: 'Odpojit',
		verticalSplit: 'Svislé rozdělení',
		video: 'Video',
		videoGallery: 'Videogalerie',
		video_modal_file: 'Vybrat ze souborů',
		video_modal_title: 'Vložit video',
		video_modal_url: 'URL pro vložení médií, YouTube/Vimeo',
		width: 'Šířka'
	};

	if (typeof noGlobal === typeof undefined) {
		if (!window.SUNEDITOR_LANG) {
			Object.defineProperty(window, 'SUNEDITOR_LANG', {
				enumerable: true,
				writable: false,
				configurable: false,
				value: {}
			});
		}

		Object.defineProperty(window.SUNEDITOR_LANG, 'cs', {
			enumerable: true,
			writable: true,
			configurable: true,
			value: lang
		});
	}

	return lang;
});
