// Hungarian
(function (global, factory) {
	if (typeof module === 'object' && typeof module.exports === 'object') {
		module.exports = global.document
			? factory(global, true)
			: function (w) {
					if (!w.document) {
						throw new Error('SUNEDITOR_LANG requires a window with a document');
					}
					return factory(w);
			  };
	} else {
		factory(global);
	}
})(typeof window !== 'undefined' ? window : this, function (window, noGlobal) {
	const lang = {
		code: 'hu',
		align: 'Igazítás',
		alignBottom: 'Alulra igazítás',
		alignCenter: 'Középre igazítás',
		alignJustify: 'Sorkizárt',
		alignLeft: 'Balra igazítás',
		alignMiddle: 'Középre igazítás',
		alignRight: 'Jobbra igazítás',
		alignTop: 'Fentről igazítás',
		anchor: 'Könyvjelző',
		asBlock: 'Blokk szintű',
		asInline: 'Sor szintű',
		asLink: 'Linkként',
		audio: 'Hang',
		audioGallery: 'Hanggaléria',
		audio_modal_file: 'Fájl feltöltés',
		audio_modal_title: 'Hang beszúrása',
		audio_modal_url: 'Hang URL',
		autoSize: 'Automatikus méret',
		backgroundColor: 'Háttérszín',
		basic: 'Alapszintű',
		blockStyle: 'Blokk stílus',
		bold: 'Félkövér',
		border: 'Körvonal',
		border_all: 'Összes oldalon körvonal',
		border_inside: 'Belső körvonal',
		border_horizontal: 'Vízszintes körvonal',
		border_vertical: 'Függőleges körvonal',
		border_outside: 'Külső körvonal',
		border_left: 'Bal oldali körvonal',
		border_top: 'Felső körvonal',
		border_right: 'Jobb oldali körvonal',
		border_bottom: 'Alsó körvonal',
		border_none: 'Nincs körvonal',
		bulletedList: 'Pontozott lista',
		cancel: 'Mégse',
		caption: 'Képaláírás beszúrása',
		cellProperties: 'Cella tulajdonságok',
		center: 'Középre',
		close: 'Bezárás',
		codeView: 'Forráskód nézet',
		color: 'Szín',
		colorPicker: 'Színválasztó',
		column: 'Oszlop',
		comment: 'Megjegyzés',
		commentAdd: 'Megjegyzés hozzáadása',
		commentShow: 'Megjegyzés megjelenítése',
		copy: 'Másolás',
		copyFormat: 'Formázás másolása',
		cut: 'Kivágás',
		default: 'Alapértelmezett',
		deleteColumn: 'Oszlop törlése',
		deleteRow: 'Sor törlése',
		dir_ltr: 'Balról jobbra',
		dir_rtl: 'Jobbról balra',
		download: 'Letöltés',
		drag: 'Húzás',
		drawing: 'Rajz',
		drawing_modal_title: 'Rajz beszúrása',
		edit: 'Szerkesztés',
		embed: 'Beágyazás',
		embed_modal_title: 'Beágyazás beszúrása',
		embed_modal_source: 'Beágyazási forrás / URL',
		exportPDF: 'PDF exportálása',
		exportWord: 'Word exportálása',
		find: 'Keresés',
		decrease: 'Csökkentés',
		increase: 'Növelés',
		fileBrowser: 'Fájl böngésző',
		fileGallery: 'Fájlgaléria',
		fileUpload: 'Fájl feltöltés',
		fixedColumnWidth: 'Rögzített oszlopszélesség',
		font: 'Betűtípus',
		fontColor: 'Betűszín',
		fontSize: 'Betűméret',
		formats: 'Formátumok',
		fullScreen: 'Teljes képernyő',
		height: 'Magasság',
		horizontalLine: 'Vízszintes vonal',
		horizontalSplit: 'Vízszintes elválasztás',
		hr_dashed: 'Szaggatott',
		hr_dotted: 'Pontozott',
		hr_solid: 'Folyamatos',
		id: 'Azonosító',
		image: 'Kép',
		imageGallery: 'Képgalléria',
		image_modal_altText: 'Alternatív szöveg',
		image_modal_file: 'Fájl feltöltés',
		image_modal_title: 'Kép beszúrása',
		image_modal_url: 'Képhivatkozás',
		importWord: 'Word importálása',
		indent: 'Behúzás növelése',
		inlineStyle: 'Inline stílus',
		insertColumnAfter: 'Oszlop beszúrása utána',
		insertColumnBefore: 'Oszlop beszúrása előtt',
		insertRowAbove: 'Sor beszúrása fölötte',
		insertRowBelow: 'Sor beszúrása alatta',
		insertLine: 'Vonal beszúrása',
		italic: 'Dőlt',
		layout: 'Elrendezés',
		left: 'Balra',
		lineHeight: 'Sormagasság',
		link: 'Link',
		link_modal_bookmark: 'Könyvjelző',
		link_modal_downloadLinkCheck: 'Letöltési link',
		link_modal_newWindowCheck: 'Új ablakban nyitás',
		link_modal_text: 'Megjelenített szöveg',
		link_modal_title: 'Link beszúrása',
		link_modal_url: 'Link URL',
		link_modal_relAttribute: 'Rel attribútum',
		list: 'Lista',
		math: 'Matematika',
		math_modal_fontSizeLabel: 'Betűméret',
		math_modal_inputLabel: 'Matematikai jelölések',
		math_modal_previewLabel: 'Előnézet',
		math_modal_title: 'Matematika',
		maxSize: 'Maximális méret',
		mediaGallery: 'Média galéria',
		mention: 'Említés',
		menu_bordered: 'Körvonalas',
		menu_code: 'Kód',
		menu_neon: 'Neon',
		menu_shadow: 'Árnyék',
		menu_spaced: 'Szellősebb',
		menu_translucent: 'Áttetsző',
		mergeCells: 'Cellák egyesítése',
		minSize: 'Minimális méret',
		mirrorHorizontal: 'Vízszintes tükrözés',
		mirrorVertical: 'Függőleges tükrözés',
		newDocument: 'Új dokumentum',
		numberedList: 'Számozott lista',
		outdent: 'Behúzás csökkentése',
		pageBreak: 'Oldaltörés',
		pageDown: 'Oldal lefelé',
		pageNumber: 'Oldalszám',
		pageUp: 'Oldal felfelé',
		paragraphStyle: 'Bekezdés stílus',
		preview: 'Előnézet',
		print: 'Nyomtatás',
		proportion: 'Méretkorlátok megtartása',
		ratio: 'Képarány',
		redo: 'Újra',
		remove: 'Eltávolítás',
		removeFormat: 'Formázás törlése',
		replace: 'Csere',
		replaceAll: 'Összes csere',
		resize100: 'Zoom 100%',
		resize25: 'Zoom 25%',
		resize50: 'Zoom 50%',
		resize75: 'Zoom 75%',
		resize: 'Átméretezés',
		revert: 'Visszaállítás',
		revisionHistory: 'Módosítási előzmények',
		right: 'Jobbra',
		rotateLeft: 'Balra forgatás',
		rotateRight: 'Jobbra forgatás',
		row: 'Sor',
		save: 'Mentés',
		search: 'Keresés',
		selectAll: 'Mindet kijelöl',
		showBlocks: 'Blokkok megjelenítése',
		size: 'Méret',
		splitCells: 'Cellák szétválasztása',
		strike: 'Áthúzott',
		submitButton: 'Küldés',
		subscript: 'Alsó index',
		superscript: 'Felső index',
		table: 'Táblázat',
		tableHeader: 'Táblázat fejléc',
		tableProperties: 'Táblázat tulajdonságok',
		tags: 'Címkék',
		tag_blockquote: 'Idézet',
		tag_div: 'Normál (DIV)',
		tag_h: 'Fejléc',
		tag_p: 'Bekezdés',
		tag_pre: 'Kód',
		template: 'Minta',
		textStyle: 'Szövegstílus',
		title: 'Cím',
		underline: 'Aláhúzott',
		undo: 'Visszavonás',
		unlink: 'Link eltávolítása',
		verticalSplit: 'Függőleges elválasztás',
		video: 'Videó',
		videoGallery: 'Videó galéria',
		video_modal_file: 'Fájl feltöltés',
		video_modal_title: 'Videó beszúrása',
		video_modal_url: 'Beágyazható URL, YouTube/Vimeo',
		width: 'Szélesség'
	};

	if (typeof noGlobal === 'undefined') {
		if (!window.SUNEDITOR_LANG) {
			Object.defineProperty(window, 'SUNEDITOR_LANG', {
				enumerable: true,
				writable: false,
				configurable: false,
				value: {}
			});
		}
		Object.defineProperty(window.SUNEDITOR_LANG, 'hu', {
			enumerable: true,
			writable: true,
			configurable: true,
			value: lang
		});
	}

	return lang;
});
