// Japanese
(function (global, factory) {
	if (typeof module === 'object' && typeof module.exports === 'object') {
		module.exports = global.document
			? factory(global, true)
			: function (w) {
					if (!w.document) {
						throw new Error('SUNEDITOR_LANG a window with a document');
					}
					return factory(w);
			  };
	} else {
		factory(global);
	}
})(typeof window !== 'undefined' ? window : this, function (window, noGlobal) {
	const lang = {
		code: 'ja',
		align: 'ソート',
		alignBottom: '下揃え',
		alignCenter: '中央揃え',
		alignJustify: '両端揃え',
		alignLeft: '左揃え',
		alignMiddle: '中央揃え',
		alignRight: '右揃え',
		alignTop: '上揃え',
		anchor: 'アンカー',
		asBlock: 'ブロックとして',
		asInline: 'インラインとして',
		asLink: 'リンクとして',
		audio: 'オーディオ',
		audioGallery: 'オーディオ ギャラリー',
		audio_modal_file: 'ファイルの選択',
		audio_modal_title: 'オーディオを挿入',
		audio_modal_url: 'オーディオアドレス',
		autoSize: '自動サイズ',
		backgroundColor: '文字の背景色',
		basic: '基本',
		blockStyle: 'ブロック スタイル',
		bold: '太字',
		border: '境界線',
		border_all: 'すべてに境界線',
		border_inside: '内側に境界線',
		border_horizontal: '水平に境界線',
		border_vertical: '垂直に境界線',
		border_outside: '外側に境界線',
		border_left: '左に境界線',
		border_top: '上に境界線',
		border_right: '右に境界線',
		border_bottom: '下に境界線',
		border_none: '境界線なし',
		bulletedList: '円形ブリット',
		cancel: 'キャンセル',
		caption: '説明付け',
		cellProperties: 'セルのプロパティ',
		center: '中央',
		close: '閉じる',
		codeView: 'HTMLの編集',
		color: '色',
		colorPicker: 'カラー ピッカー',
		column: '列',
		comment: 'コメント',
		commentAdd: 'コメントを追加',
		commentShow: 'コメントを表示',
		copy: 'コピー',
		copyFormat: 'ペイント 書式設定',
		cut: '切り取り',
		default: 'デフォルト',
		deleteColumn: '列を削除する',
		deleteRow: '行の削除',
		dir_ltr: '左から右へ',
		dir_rtl: '右から左に',
		download: 'ダウンロード',
		drag: 'ドラッグ',
		drawing: '描画',
		drawing_modal_title: '描画',
		edit: '編集',
		embed: '埋め込み',
		embed_modal_title: '埋め込み',
		embed_modal_source: '埋め込みソース / URL',
		exportPDF: 'PDF にエクスポート',
		exportWord: 'Word にエクスポート',
		find: '検索',
		decrease: '縮小',
		increase: '拡大',
		fileBrowser: 'ファイル ブラウザー',
		fileGallery: 'ファイル ギャラリー',
		fileUpload: 'ファイルのアップロード',
		fixedColumnWidth: '固定列幅',
		font: 'フォント',
		fontColor: '文字色',
		fontSize: 'サイズ',
		formats: '段落形式',
		fullScreen: 'フルスクリーン',
		height: '縦',
		horizontalLine: '水平線を挿入',
		horizontalSplit: '横分割',
		hr_dashed: 'ダッシュ',
		hr_dotted: '点線',
		hr_solid: '実線',
		id: 'ID',
		image: '画像',
		imageGallery: 'イメージギャラリー',
		image_modal_altText: '置換文字列',
		image_modal_file: 'ファイルの選択',
		image_modal_title: '画像の挿入',
		image_modal_url: 'イメージアドレス',
		importWord: 'Word からインポート',
		indent: 'インデント',
		inlineStyle: 'インライン スタイル',
		insertColumnAfter: '右に列を挿入',
		insertColumnBefore: '左に列を挿入',
		insertRowAbove: '上に行を挿入',
		insertRowBelow: '下に行を挿入',
		insertLine: '行の挿入',
		italic: 'イタリック',
		layout: 'レイアウト',
		left: '左',
		lineHeight: '行の高さ',
		link: 'リンク',
		link_modal_bookmark: 'ブックマーク',
		link_modal_downloadLinkCheck: 'ダウンロードリンク',
		link_modal_newWindowCheck: '別ウィンドウで開く',
		link_modal_text: '画面のテキスト',
		link_modal_title: 'リンクの挿入',
		link_modal_url: 'インターネットアドレス',
		link_modal_relAttribute: 'Rel 属性',
		list: 'リスト',
		math: '数学',
		math_modal_fontSizeLabel: 'サイズ',
		math_modal_inputLabel: '数学表記',
		math_modal_previewLabel: 'プレビュー',
		math_modal_title: '数学',
		maxSize: '最大サイズ',
		mediaGallery: 'メディア ギャラリー',
		mention: '言及する',
		menu_bordered: '境界線',
		menu_code: 'コード',
		menu_neon: 'ネオン',
		menu_shadow: '影',
		menu_spaced: '文字間隔',
		menu_translucent: '半透明',
		mergeCells: 'セルの結合',
		minSize: '最小サイズ',
		mirrorHorizontal: '左右反転',
		mirrorVertical: '上下反転',
		newDocument: '新規ドキュメント',
		numberedList: '数値ブリット',
		outdent: 'インデント',
		pageBreak: 'ページ区切り',
		pageDown: 'ページを 1 ページ下へ',
		pageNumber: 'ページ番号',
		pageUp: 'ページを 1 ページ上へ',
		paragraphStyle: '段落スタイル',
		preview: 'プレビュー',
		print: '印刷',
		proportion: 'の割合カスタマイズ',
		ratio: '比率',
		redo: '再実行',
		remove: '削除',
		removeFormat: '形式を削除',
		replace: '置換',
		replaceAll: 'すべて置換',
		resize100: '100％ サイズ',
		resize25: '25％ サイズ',
		resize50: '50％ サイズ',
		resize75: '75％ サイズ',
		resize: 'サイズ変更',
		revert: '元に戻す',
		revisionHistory: 'リビジョン履歴',
		right: '右',
		rotateLeft: '左に回転',
		rotateRight: '右に回転',
		row: '行',
		save: '保存',
		search: '探す',
		selectAll: 'すべて選択',
		showBlocks: 'ブロック表示',
		size: 'サイズ',
		splitCells: 'セルを分割',
		strike: '取り消し線',
		submitButton: '確認',
		subscript: '下付き',
		superscript: '上付き',
		table: 'テーブル',
		tableHeader: '表のヘッダー',
		tableProperties: '表のプロパティ',
		tags: 'タグ',
		tag_blockquote: '引用',
		tag_div: '基本（DIV）',
		tag_h: 'タイトル',
		tag_p: '本文',
		tag_pre: 'コード',
		template: 'テンプレート',
		textStyle: 'テキストスタイル',
		title: 'タイトル',
		underline: '下線',
		undo: '元に戻す',
		unlink: 'リンク解除',
		verticalSplit: '垂直分割',
		video: '動画',
		videoGallery: 'ビデオ ギャラリー',
		video_modal_file: 'ファイルの選択',
		video_modal_title: '動画を挿入',
		video_modal_url: 'メディア埋め込みアドレス, YouTube/Vimeo',
		width: '横'
	};

	if (typeof noGlobal === typeof undefined) {
		if (!window.SUNEDITOR_LANG) {
			Object.defineProperty(window, 'SUNEDITOR_LANG', {
				enumerable: true,
				writable: false,
				configurable: false,
				value: {}
			});
		}

		Object.defineProperty(window.SUNEDITOR_LANG, 'ja', {
			enumerable: true,
			writable: true,
			configurable: true,
			value: lang
		});
	}

	return lang;
});
