// Khmer
(function (global, factory) {
	if (typeof module === 'object' && typeof module.exports === 'object') {
		module.exports = global.document
			? factory(global, true)
			: function (w) {
					if (!w.document) {
						throw new Error('SUNEDITOR_LANG a window with a document');
					}
					return factory(w);
				};
	} else {
		factory(global);
	}
})(typeof window !== 'undefined' ? window : this, function (window, noGlobal) {
	const lang = {
		code: 'km',
		align: 'តម្រឹម',
		alignBottom: 'តម្រឹមបាត',
		alignCenter: 'តម្រឹមចំកណ្តាល',
		alignJustify: 'តម្រឹមស្មើរ',
		alignLeft: 'តម្រឹមឆ្វេង',
		alignMiddle: 'តម្រឹមពាក់កណ្តាល',
		alignRight: 'តម្រឹមស្ដាំ',
		alignTop: 'តម្រឹមកំពូល',
		anchor: 'យុថ្កា',
		asBlock: 'ជា​ប្លក់',
		asInline: 'ជាជួរ',
		asLink: 'ជា​តំណ',
		audio: 'អូឌីយូ',
		audioGallery: 'វិចិត្រសាលអូឌីយ៉ូ',
		audio_modal_file: 'ជ្រើសរើសពីឯកសារ',
		audio_modal_title: 'បញ្ចូលអូឌីយូ',
		audio_modal_url: 'URL អូឌីយូ',
		autoSize: 'ទំហំស្វ័យប្រវត្តិ',
		backgroundColor: 'ពណ៌ផ្ទៃខាងក្រោយ',
		basic: 'មូលដ្ឋាន',
		blockStyle: 'រចនាប័ទ្មប្លក់',
		bold: 'អក្សរដិត',
		border: 'ស៊ុម',
		border_all: 'ស៊ុមទាំងអស់',
		border_inside: 'ស៊ុមក្នុង',
		border_horizontal: 'ស៊ុមផ្តេក',
		border_vertical: 'ស៊ុមបញ្ឈរ',
		border_outside: 'ស៊ុមក្រៅ',
		border_left: 'ស៊ុមឆ្វេង',
		border_top: 'ស៊ុមលើ',
		border_right: 'ស៊ុមស្ដាំ',
		border_bottom: 'ស៊ុមក្រោម',
		border_none: 'គ្មានស៊ុម',
		bulletedList: 'បញ្ជីជាចំណុច',
		cancel: 'បោះបង់',
		caption: 'បញ្ចូលការពិពណ៌នា',
		cellProperties: 'លក្ខណៈក្រឡា',
		center: 'កណ្តាល',
		close: 'បិទ',
		codeView: 'មើលកូដ',
		color: 'ពណ៌',
		colorPicker: 'ឧបករណ៍ជ្រើសពណ៌',
		column: 'ជួរឈរ',
		comment: 'មតិ',
		commentAdd: 'បន្ថែមមតិ',
		commentShow: 'បង្ហាញមតិ',
		copy: 'ចម្លង',
		copyFormat: 'ចម្លងទ្រង់ទ្រាយ',
		cut: 'កាត់',
		default: 'លំនាំដើម',
		deleteColumn: 'លុបជួរឈរ',
		deleteRow: 'លុបជួរដេក',
		dir_ltr: 'ពីឆ្វេងទៅស្តាំ',
		dir_rtl: 'ពីស្តាំទៅឆ្វេង',
		download: 'ទាញយក',
		drag: 'អូស',
		drawing: 'គូរ',
		drawing_modal_title: 'គូរ',
		edit: 'កែសម្រួល',
		embed: 'បង្កប់',
		embed_modal_title: 'បង្កប់',
		embed_modal_source: 'ប្រភពសម្រាប់បង្កប់ / URL',
		exportPDF: 'បញ្ចេញជា PDF',
		exportWord: 'បញ្ចេញជា Word',
		find: 'ស្វែងរក',
		decrease: 'បន្ថយ',
		increase: 'បន្ថែម',
		fileBrowser: 'កម្មវិធីរុករកឯកសារ',
		fileGallery: 'វិចិត្រសាលឯកសារ',
		fileUpload: 'ផ្ទុកឯកសារឡើង',
		fixedColumnWidth: 'ទទឹងជួរឈរថេរ',
		font: 'ពុម្ព',
		fontColor: 'ពណ៌អក្សរ',
		fontSize: 'ទំហំ',
		formats: 'ទ្រង់ទ្រាយ',
		fullScreen: 'ពេញអេក្រង់',
		height: 'កម្ពស់',
		horizontalLine: 'បន្ទាត់ផ្តេក',
		horizontalSplit: 'បំបែកផ្តេក',
		hr_dashed: 'បន្ទាត់ដាច់',
		hr_dotted: 'បន្ទាត់ចំណុច',
		hr_solid: 'បន្ទាត់ធម្មតា',
		id: 'ID',
		image: 'រូបភាព',
		imageGallery: 'វិចិត្រសាលរូបភាព',
		image_modal_altText: 'អត្ថបទជំនួសរូបភាព',
		image_modal_file: 'ជ្រើសរើសពីឯកសារ',
		image_modal_title: 'បញ្ចូលរូបភាព',
		image_modal_url: 'URL រូបភាព',
		importWord: 'បញ្ចូលពី Word',
		indent: 'ចូលបន្ទាត់',
		inlineStyle: 'រចនាប័ទ្មក្នុងជួរបន្ទាត់',
		insertColumnAfter: 'បញ្ចូលជួរឈរ​ក្រោយ',
		insertColumnBefore: 'បញ្ចូលជួរឈរ​មុន',
		insertRowAbove: 'បញ្ចូលជួរដេក​លើ',
		insertRowBelow: 'បញ្ចូលជួរដេក​ក្រោម',
		insertLine: 'បញ្ចូលបន្ទាត់',
		italic: 'ទ្រេត',
		layout: 'ប្លង់',
		left: 'ឆ្វេង',
		lineHeight: 'កម្ពស់បន្ទាត់',
		link: 'តំណ',
		link_modal_bookmark: 'ចំណាំ',
		link_modal_downloadLinkCheck: 'តំណទាញយក',
		link_modal_newWindowCheck: 'បើកក្នុងផ្ទាំងថ្មី',
		link_modal_text: 'អត្ថបទបង្ហាញ',
		link_modal_title: 'បញ្ចូលតំណ',
		link_modal_url: 'URL តំណ',
		link_modal_relAttribute: 'លក្ខណៈ Rel',
		list: 'បញ្ជី',
		math: 'គណិត',
		math_modal_fontSizeLabel: 'ទំហំពុម្ព',
		math_modal_inputLabel: 'សញ្ញាណគណិត',
		math_modal_previewLabel: 'មើលជាមុន',
		math_modal_title: 'គណិត',
		maxSize: 'ទំហំធំ',
		mediaGallery: 'វិចិត្រសាលមេឌៀ',
		mention: 'លើកឡើង',
		menu_bordered: 'មានស៊ុម',
		menu_code: 'កូដ',
		menu_neon: 'ពន្លឺ',
		menu_shadow: 'ស្រមោល',
		menu_spaced: 'ចន្លោះ',
		menu_translucent: 'ថ្លា',
		mergeCells: 'បញ្ចូលក្រឡា',
		minSize: 'ទំហំតិច',
		mirrorHorizontal: 'បញ្ច្រាសផ្ដេក',
		mirrorVertical: 'បញ្ច្រាសបញ្ឈរ',
		newDocument: 'ឯកសារថ្មី',
		numberedList: 'បញ្ជីជាលេខ',
		outdent: 'ចេញបន្ទាត់',
		pageBreak: 'បំបែកទំព័រ',
		pageDown: 'ទំព័រក្រោម',
		pageNumber: 'លេខទំព័រ',
		pageUp: 'ទំព័រលើ',
		paragraphStyle: 'រចនាប័ទ្មកថាខណ្ឌ',
		preview: 'មើលជាមុន',
		print: 'បោះពុម្ព',
		proportion: 'កំណត់សមាមាត្រ',
		ratio: 'សមាមាត្រ',
		redo: 'ធ្វើឡើងវិញ',
		remove: 'លុប',
		removeFormat: 'លុបទ្រង់ទ្រាយ',
		replace: 'ជំនួស',
		replaceAll: 'ជំនួសទាំងអស់',
		resize100: 'ពង្រីក ១០០%',
		resize25: 'ពង្រីក ២៥%',
		resize50: 'ពង្រីក ៥០%',
		resize75: 'ពង្រីក ៧៥%',
		resize: 'ប្តូរទំហំ',
		revert: 'ត្រឡប់',
		revisionHistory: 'ប្រវត្តិកែប្រែ',
		right: 'ស្តាំ',
		rotateLeft: 'បង្វិលឆ្វេង',
		rotateRight: 'បង្វិលស្តាំ',
		row: 'ជួរដេក',
		save: 'រក្សាទុក',
		search: 'ស្វែងរក',
		selectAll: 'ជ្រើសរើសទាំងអស់',
		showBlocks: 'បង្ហាញប្លក់',
		size: 'ទំហំ',
		splitCells: 'បំបែកក្រឡា',
		strike: 'ឆូតអក្សរ',
		submitButton: 'ដាក់ស្នើ',
		subscript: 'អក្សរតូចក្រោម',
		superscript: 'អក្សរតូចលើ',
		table: 'តារាង',
		tableHeader: 'ក្បាលតារាង',
		tableProperties: 'លក្ខណៈតារាង',
		tags: 'ស្លាក',
		tag_blockquote: 'សម្រង់',
		tag_div: 'ធម្មតា (DIV)',
		tag_h: 'ក្បាល',
		tag_p: 'កថាខណ្ឌ',
		tag_pre: 'កូដ',
		template: 'គំរូ',
		textStyle: 'រចនាប័ទ្មអក្សរ',
		title: 'ចំណងជើង',
		underline: 'បន្ទាត់ក្រោម',
		undo: 'មិនធ្វើវិញ',
		unmergeCells: 'ផ្តាច់ក្រឡា',
		unlink: 'ផ្តាច់តំណ',
		verticalSplit: 'បំបែកបញ្ឈរ',
		video: 'វីដេអូ',
		videoGallery: 'វិចិត្រសាលវីដេអូ',
		video_modal_file: 'ជ្រើសរើសពីឯកសារ',
		video_modal_title: 'បញ្ចូលវីដេអូ',
		video_modal_url: 'URL បង្កប់មេឌៀ, YouTube/Vimeo',
		width: 'ទទឹង',
		message_copy_success: 'បានចម្លងទៅក្តារចម្លង',
		message_copy_fail: 'ការចម្លងបរាជ័យ។ សូមចម្លងដោយដៃ។',
	};

	if (typeof noGlobal === typeof undefined) {
		if (!window.SUNEDITOR_LANG) {
			Object.defineProperty(window, 'SUNEDITOR_LANG', {
				enumerable: true,
				writable: false,
				configurable: false,
				value: {},
			});
		}

		Object.defineProperty(window.SUNEDITOR_LANG, 'km', {
			enumerable: true,
			writable: true,
			configurable: true,
			value: lang,
		});
	}

	return lang;
});
