// Latvia
(function (global, factory) {
	if (typeof module === 'object' && typeof module.exports === 'object') {
		module.exports = global.document
			? factory(global, true)
			: function (w) {
					if (!w.document) {
						throw new Error('SUNEDITOR_LANG a window with a document');
					}
					return factory(w);
			  };
	} else {
		factory(global);
	}
})(typeof window !== 'undefined' ? window : this, function (window, noGlobal) {
	const lang = {
		code: 'lv',
		align: 'Izlīdzināt',
		alignBottom: 'Izlīdziniet apakšējo daļu',
		alignCenter: 'Centrēt',
		alignJustify: 'Taisnot',
		alignLeft: 'Līdzināt pa kreisi',
		alignMiddle: 'Izlīdzināt vidū',
		alignRight: 'Līdzināt pa labi',
		alignTop: 'Izlīdziniet augšdaļu',
		anchor: 'Enkurs',
		asBlock: 'Kā bloks',
		asInline: 'Kā iekļauts',
		asLink: 'Kā saite',
		audio: 'Audio',
		audioGallery: 'Audio galerija',
		audio_modal_file: 'Izvēlieties no failiem',
		audio_modal_title: 'Ievietot audio',
		audio_modal_url: 'Audio URL',
		autoSize: 'Automātiskais izmērs',
		backgroundColor: 'Teksta iezīmēšanas krāsa',
		basic: 'Nav iesaiņojuma',
		blockStyle: 'Bloka stils',
		bold: 'Treknraksts',
		border: 'Robeža',
		border_all: 'Robeža visu',
		border_inside: 'Robeža iekšā',
		border_horizontal: 'Robeža horizontāla',
		border_vertical: 'Apmale vertikāla',
		border_outside: 'Robeža ārpusē',
		border_left: 'Robeža pa kreisi',
		border_top: 'Apmales augšdaļa',
		border_right: 'Robeža pa labi',
		border_bottom: 'Apmales apakšdaļa',
		border_none: 'Robežas nav',
		bulletedList: 'Aizzimes',
		cancel: 'Atcelt',
		caption: 'Ievietot aprakstu',
		cellProperties: 'Šūnu īpašības',
		center: 'Centrs',
		close: 'Aizvērt',
		codeView: 'Koda skats',
		color: 'Krāsa',
		colorPicker: 'Krāsu atlasītājs',
		column: 'Kolonna',
		comment: 'komentāri',
		commentAdd: 'Pievienot komentāru',
		commentShow: 'Rādīt komentārus',
		copy: 'Kopēt',
		copyFormat: 'Krāsu formatēšana',
		cut: 'Izgriezt',
		default: 'Noklusējuma',
		deleteColumn: 'Dzēst kolonnu',
		deleteRow: 'Dzēst rindu',
		dir_ltr: 'No kreisās uz labo',
		dir_rtl: 'No labās uz kreiso',
		download: 'Lejupielādēt',
		drag: 'Velciet',
		drawing: 'Zīmējums',
		drawing_modal_title: 'Zīmējums',
		edit: 'Rediģēt',
		embed: 'Iegult',
		embed_modal_title: 'Iegult',
		embed_modal_source: 'Iegult avotu / URL',
		exportPDF: 'Eksportēt uz PDF',
		exportWord: 'Eksportēt uz Word',
		find: 'Atrast',
		decrease: 'Samazināt',
		increase: 'Palielināt',
		fileBrowser: 'Failu pārlūks',
		fileGallery: 'Failu galerija',
		fileUpload: 'Failu augšupielāde',
		fixColumnWidth: 'Fiksēts kolonnas platums',
		font: 'Fonts',
		fontColor: 'Fonta krāsa',
		fontSize: 'Fonta lielums',
		formats: 'Formāti',
		fullScreen: 'Pilnekrāna režīms',
		height: 'Augstums',
		horizontalLine: 'Horizontāla līnija',
		horizontalSplit: 'Horizontāls sadalījums',
		hr_dashed: 'Braša',
		hr_dotted: 'Punktiņš',
		hr_solid: 'Ciets',
		id: 'ID',
		image: 'Attēls',
		imageGallery: 'Attēlu galerija',
		image_modal_altText: 'Alternatīvs teksts',
		image_modal_file: 'Izvēlieties no failiem',
		image_modal_title: 'Ievietot attēlu',
		image_modal_url: 'Attēla URL',
		importWord: 'Importēt no Word',
		indent: 'Palielināt atkāpi',
		inlineStyle: 'Iekļauts stils',
		insertColumnAfter: 'Ievietot kolonnu aiz',
		insertColumnBefore: 'Ievietot kolonnu pirms',
		insertRowAbove: 'Ievietot rindu virs',
		insertRowBelow: 'Ievietot rindu zemāk',
		insertLine: 'Ievietojiet rindu',
		italic: 'Slīpraksts',
		layout: 'Izkārtojums',
		left: 'Pa kreisi',
		lineHeight: 'Līnijas augstums',
		link: 'Saite',
		link_modal_bookmark: 'Grāmatzīme',
		link_modal_downloadLinkCheck: 'Lejupielādes saite',
		link_modal_newWindowCheck: 'Atvērt jaunā logā',
		link_modal_text: 'Parādāmais teksts',
		link_modal_title: 'Ievietot saiti',
		link_modal_url: 'Saites URL',
		link_modal_relAttribute: 'Rel atribūts',
		list: 'Saraksts',
		math: 'Matemātika',
		math_modal_fontSizeLabel: 'Fonta lielums',
		math_modal_inputLabel: 'Matemātiskā notācija',
		math_modal_previewLabel: 'Priekšskatījums',
		math_modal_title: 'Matemātika',
		maxSize: 'Maksimālais izmērs',
		mediaGallery: 'Mediju galerija',
		mention: 'Pieminēt',
		menu_bordered: 'Robežojās',
		menu_code: 'Kods',
		menu_neon: 'Neona',
		menu_shadow: 'Ēna',
		menu_spaced: 'Ar atstarpi',
		menu_translucent: 'Caurspīdīgs',
		mergeCells: 'Apvienot šūnas',
		minSize: 'Minimālais izmērs',
		mirrorHorizontal: 'Spogulis, horizontāls',
		mirrorVertical: 'Spogulis, vertikāls',
		newDocument: 'Jauns dokuments',
		numberedList: 'Numerācija',
		outdent: 'Samazināt atkāpi',
		pageBreak: 'Lapas pārtraukums',
		pageDown: 'Lapa uz leju',
		pageNumber: 'Lapas numurs',
		pageUp: 'Lapa uz augšu',
		paragraphStyle: 'Paragrāfa stils',
		preview: 'Priekšskatījums',
		print: 'Drukāt',
		proportion: 'Ierobežo proporcijas',
		ratio: 'Attiecība',
		redo: 'Atkārtot',
		remove: 'Noņemt',
		removeFormat: 'Noņemt formātu',
		replace: 'Aizstāt',
		replaceAll: 'Aizstāt visu',
		resize100: 'Mainīt izmēru 100%',
		resize25: 'Mainīt izmēru 25%',
		resize50: 'Mainīt izmēru 50%',
		resize75: 'Mainīt izmēru 75%',
		resize: 'Mainīt izmērus',
		revert: 'Atjaunot',
		revisionHistory: 'Pārskatīšanas vēsture',
		right: 'Labajā pusē',
		rotateLeft: 'Pagriezt pa kreisi',
		rotateRight: 'Pagriezt pa labi',
		row: 'Rinda',
		save: 'Saglabāt',
		search: 'Meklēt',
		selectAll: 'Atlasiet visu',
		showBlocks: 'Parādit blokus',
		size: 'Izmērs',
		splitCells: 'Sadalīt šūnas',
		strike: 'Pārsvītrojums',
		submitButton: 'Iesniegt',
		subscript: 'Apakšraksts',
		superscript: 'Augšraksts',
		table: 'Tabula',
		tableHeader: 'Tabulas galvene',
		tableProperties: 'Tabulas īpašības',
		tags: 'Tagi',
		tag_blockquote: 'Citāts',
		tag_div: 'Normāli (DIV)',
		tag_h: 'Galvene',
		tag_p: 'Paragrāfs',
		tag_pre: 'Kods',
		template: 'Veidne',
		textStyle: 'Teksta stils',
		title: 'Nosaukums',
		underline: 'Pasvītrot',
		undo: 'Atsaukt',
		unlink: 'Atsaistīt',
		verticalSplit: 'Vertikāls sadalījums',
		video: 'Video',
		videoGallery: 'Video galerija',
		video_modal_file: 'Izvēlieties no failiem',
		video_modal_title: 'Ievietot video',
		video_modal_url: 'Multivides iegulšanas URL, YouTube/Vimeo',
		width: 'Platums'
	};

	if (typeof noGlobal === typeof undefined) {
		if (!window.SUNEDITOR_LANG) {
			Object.defineProperty(window, 'SUNEDITOR_LANG', {
				enumerable: true,
				writable: false,
				configurable: false,
				value: {}
			});
		}

		Object.defineProperty(window.SUNEDITOR_LANG, 'lv', {
			enumerable: true,
			writable: true,
			configurable: true,
			value: lang
		});
	}

	return lang;
});
