// Portuguese (Brazil)
(function (global, factory) {
	if (typeof module === 'object' && typeof module.exports === 'object') {
		module.exports = global.document
			? factory(global, true)
			: function (w) {
					if (!w.document) {
						throw new Error('SUNEDITOR_LANG a window with a document');
					}
					return factory(w);
			  };
	} else {
		factory(global);
	}
})(typeof window !== 'undefined' ? window : this, function (window, noGlobal) {
	const lang = {
		code: 'pt_br',
		align: 'Alinhar',
		alignBottom: 'Alinhar inferior',
		alignCenter: 'Centralizar',
		alignJustify: 'Justificar',
		alignLeft: 'Alinhar à esquerda',
		alignMiddle: 'Alinhar central',
		alignRight: 'Alinhar à direita',
		alignTop: 'Alinhar superior',
		anchor: 'Âncora',
		asBlock: 'Como um bloco',
		asInline: 'Como um inline',
		asLink: 'Como um link',
		audio: 'Áudio',
		audioGallery: 'Galeria de áudio',
		audio_modal_file: 'Selecionar arquivos',
		audio_modal_title: 'Inserir áudio',
		audio_modal_url: 'URL da áudio',
		autoSize: 'Tamanho automático',
		backgroundColor: 'Cor de destaque',
		basic: 'Básico',
		blockStyle: 'Estilo de bloco',
		bold: 'Negrito',
		border: 'Borda',
		border_all: 'Borda tudo',
		border_inside: 'Borda interna',
		border_horizontal: 'Borda horizontal',
		border_vertical: 'Borda vertical',
		border_outside: 'Borda externa',
		border_left: 'Borda esquerda',
		border_top: 'Borda superior',
		border_right: 'Borda direita',
		border_bottom: 'Borda inferior',
		border_none: 'Borda nenhuma',
		bulletedList: 'Lista desordenada',
		cancel: 'Cancelar',
		caption: 'Inserir descrição',
		cellProperties: 'Propriedades da célula',
		center: 'Centro',
		close: 'Fechar',
		codeView: 'Mostrar códigos',
		color: 'Cor',
		colorPicker: 'Seletor de cores',
		column: 'Coluna',
		comment: 'Comentários',
		commentAdd: 'Adicionar comentário',
		commentShow: 'Mostrar comentários',
		copy: 'Copiar',
		copyFormat: 'Pintar Formatação',
		cut: 'Cortar',
		default: 'Padrão',
		deleteColumn: 'Deletar coluna',
		deleteRow: 'Deletar linha',
		dir_ltr: 'Esquerda para direita',
		dir_rtl: 'Direita para esquerda',
		download: 'Baixar',
		drag: 'Arrastar',
		drawing: 'Desenho',
		drawing_modal_title: 'Desenho',
		edit: 'Editar',
		embed: 'Incorporar',
		embed_modal_title: 'Incorporar',
		embed_modal_source: 'Incorporar Fonte / URL',
		exportPDF: 'Exportar para PDF',
		exportWord: 'Exportar para Word',
		find: 'Localizar',
		decrease: 'Diminuir',
		increase: 'Aumentar',
		fileBrowser: 'Navegador de arquivos',
		fileGallery: 'Galeria de arquivos',
		fileUpload: 'Upload de arquivo',
		fixedColumnWidth: 'Largura fixa da coluna',
		font: 'Fonte',
		fontColor: 'Cor da Fonte',
		fontSize: 'Tamanho',
		formats: 'Formatos',
		fullScreen: 'Tela cheia',
		height: 'Altura',
		horizontalLine: 'Linha horizontal',
		horizontalSplit: 'Divisão horizontal',
		hr_dashed: 'tracejada',
		hr_dotted: 'pontilhada',
		hr_solid: 'sólida',
		id: 'ID',
		image: 'Imagem',
		imageGallery: 'Galeria de imagens',
		image_modal_altText: 'Texto alternativo',
		image_modal_file: 'Selecionar arquivos',
		image_modal_title: 'Inserir imagens',
		image_modal_url: 'URL da imagem',
		importWord: 'Importar do Word',
		indent: 'Recuo',
		inlineStyle: 'Estilo inline',
		insertColumnAfter: 'Inserir coluna depois',
		insertColumnBefore: 'Inserir coluna antes',
		insertRowAbove: 'Inserir linha acima',
		insertRowBelow: 'Inserir linha abaixo',
		insertLine: 'Inserir linha',
		italic: 'Itálico',
		layout: 'Layout',
		left: 'Esquerda',
		lineHeight: 'Altura da linha',
		link: 'Link',
		link_modal_bookmark: 'marcar páginas',
		link_modal_downloadLinkCheck: 'Link para Download',
		link_modal_newWindowCheck: 'Abrir em nova guia',
		link_modal_text: 'Texto a mostrar',
		link_modal_title: 'Inserir link',
		link_modal_url: 'URL para o link',
		link_modal_relAttribute: 'Atributo rel',
		list: 'Lista',
		math: 'Matemática',
		math_modal_fontSizeLabel: 'Tamanho',
		math_modal_inputLabel: 'Notação matemática',
		math_modal_previewLabel: 'Prever',
		math_modal_title: 'Matemática',
		maxSize: 'Tam máx',
		mediaGallery: 'Galeria de mídia',
		mention: 'Menção',
		menu_bordered: 'Com borda',
		menu_code: 'Código',
		menu_neon: 'Neon',
		menu_shadow: 'Sombreado',
		menu_spaced: 'Espaçado',
		menu_translucent: 'Translúcido',
		mergeCells: 'Mesclar células',
		minSize: 'Tam mín',
		mirrorHorizontal: 'Espelho, Horizontal',
		mirrorVertical: 'Espelho, Vertical',
		newDocument: 'Novo documento',
		numberedList: 'Lista ordenada',
		outdent: 'Avançar',
		pageBreak: 'Quebra de página',
		pageDown: 'Página para baixo',
		pageNumber: 'Número da página',
		pageUp: 'Página para cima',
		paragraphStyle: 'Estilo do parágrafo',
		preview: 'Prever',
		print: 'Imprimir',
		proportion: 'Restringir proporções',
		ratio: 'Proporções',
		redo: 'Refazer',
		remove: 'Remover',
		removeFormat: 'Remover Formatação',
		replace: 'Substituir',
		replaceAll: 'Substituir todos',
		resize100: 'Zoom 100%',
		resize25: 'Zoom 25%',
		resize50: 'Zoom 50%',
		resize75: 'Zoom 75%',
		resize: 'Redimensionar',
		revert: 'Reverter',
		revisionHistory: 'Histórico de revisão',
		right: 'Direita',
		rotateLeft: 'Girar para esquerda',
		rotateRight: 'Girar para direita',
		row: 'Linha',
		save: 'Salvar',
		search: 'Procurar',
		selectAll: 'Selecionar tudo',
		showBlocks: 'Mostrar blocos',
		size: 'Tamanho',
		splitCells: 'Dividir células',
		strike: 'Riscado',
		submitButton: 'Enviar',
		subscript: 'Subescrito',
		superscript: 'Sobrescrito',
		table: 'Tabela',
		tableHeader: 'Cabeçalho da tabela',
		tableProperties: 'Propriedades da tabela',
		tags: 'Tag',
		tag_blockquote: 'Citar',
		tag_div: '(DIV) Normal',
		tag_h: 'Cabeçalho',
		tag_p: 'Paragráfo',
		tag_pre: 'Código',
		template: 'Modelo',
		textStyle: 'Estilo do texto',
		title: 'Título',
		underline: 'Sublinhado',
		undo: 'Voltar',
		unlink: 'Remover link',
		verticalSplit: 'Divisão vertical',
		video: 'Vídeo',
		videoGallery: 'Galeria de vídeos',
		video_modal_file: 'Selecionar arquivos',
		video_modal_title: 'Inserir vídeo',
		video_modal_url: 'URL do YouTube/Vimeo',
		width: 'Largura'
	};

	if (typeof noGlobal === typeof undefined) {
		if (!window.SUNEDITOR_LANG) {
			Object.defineProperty(window, 'SUNEDITOR_LANG', {
				enumerable: true,
				writable: false,
				configurable: false,
				value: {}
			});
		}

		Object.defineProperty(window.SUNEDITOR_LANG, 'pt_br', {
			enumerable: true,
			writable: true,
			configurable: true,
			value: lang
		});
	}

	return lang;
});
