// Sweden
(function (global, factory) {
	if (typeof module === 'object' && typeof module.exports === 'object') {
		module.exports = global.document
			? factory(global, true)
			: function (w) {
					if (!w.document) {
						throw new Error('SUNEDITOR_LANG a window with a document');
					}
					return factory(w);
			  };
	} else {
		factory(global);
	}
})(typeof window !== 'undefined' ? window : this, function (window, noGlobal) {
	const lang = {
		code: 'se',
		align: 'Justering',
		alignBottom: 'Rikta in botten',
		alignCenter: 'Mittenjusteirng',
		alignJustify: 'Justera indrag',
		alignLeft: 'Vänsterjustering',
		alignMiddle: 'Justera mitten',
		alignRight: 'Högerjustering',
		alignTop: 'Rikta upp toppen',
		anchor: 'Förankra',
		asBlock: 'Som ett block',
		asInline: 'Som en inline',
		asLink: 'Som länk',
		audio: 'Ljud',
		audioGallery: 'Ljudgalleri',
		audio_modal_file: 'Lägg till från fil',
		audio_modal_title: 'Lägg till ljud',
		audio_modal_url: 'Lägg till från URL',
		autoSize: 'Autostorlek',
		backgroundColor: 'Bakgrundsfärg',
		basic: 'Basic',
		blockStyle: 'Block stil',
		bold: 'Fet',
		border: 'Gräns',
		border_all: 'Gränsa alla',
		border_inside: 'Kant inuti',
		border_horizontal: 'Kant horisontell',
		border_vertical: 'Kant vertikal',
		border_outside: 'Gräns ​​utanför',
		border_left: 'Kant till vänster',
		border_top: 'Border topp',
		border_right: 'Kant till höger',
		border_bottom: 'Kant botten',
		border_none: 'Gränser ingen',
		bulletedList: 'Oordnad lista',
		cancel: 'Avboka',
		caption: 'Lägg till beskrivning',
		cellProperties: 'Cellegenskaper',
		center: 'Centrum',
		close: 'Stäng',
		codeView: 'Visa koder',
		color: 'Färg',
		colorPicker: 'Färgväljare',
		column: 'Kolumn',
		comment: 'Kommentarer',
		commentAdd: 'Lägg till kommentar',
		commentShow: 'Visa kommentarer',
		copy: 'Kopiera',
		copyFormat: 'Målarformatering',
		cut: 'Skära',
		default: 'Default',
		deleteColumn: 'Ta bort kolumner',
		deleteRow: 'Ta bort rad',
		dir_ltr: 'Vänster till höger',
		dir_rtl: 'Höger till vänster',
		download: 'Ladda ner',
		drag: 'Dra',
		drawing: 'Ritning',
		drawing_modal_title: 'Ritning',
		edit: 'Redigera',
		embed: 'Bädda in',
		embed_modal_title: 'Bädda in',
		embed_modal_source: 'Bädda in källa / URL',
		exportPDF: 'Exportera till PDF',
		exportWord: 'Exportera till Word',
		find: 'Hitta',
		decrease: 'Minska',
		increase: 'Öka',
		fileBrowser: 'Filläsare',
		fileGallery: 'Filgalleri',
		fileUpload: 'Filuppladdning',
		fixedColumnWidth: 'Fast kolumnbredd',
		font: 'Typsnitt',
		fontColor: 'Textfärg',
		fontSize: 'Textstorlek',
		formats: 'Format',
		fullScreen: 'Helskärm',
		height: 'Höjd',
		horizontalLine: 'Horisontell linje',
		horizontalSplit: 'Separera horisontalt',
		hr_dashed: 'Prickad',
		hr_dotted: 'Punkter',
		hr_solid: 'Solid',
		id: 'ID',
		image: 'Bild',
		imageGallery: 'Bildgalleri',
		image_modal_altText: 'Alternativ text',
		image_modal_file: 'Lägg till från fil',
		image_modal_title: 'Lägg till bild',
		image_modal_url: 'Lägg till från URL',
		importWord: 'Importera från Word',
		indent: 'Minska indrag',
		inlineStyle: 'Inline stil',
		insertColumnAfter: 'Lägg till kolumn efter',
		insertColumnBefore: 'Lägg till kolumn före',
		insertRowAbove: 'Lägg till rad över',
		insertRowBelow: 'Lägg till rad under',
		insertLine: 'Infoga linje',
		italic: 'Kursiv',
		layout: 'Layout',
		left: 'Vänster',
		lineHeight: 'Linjehöjd',
		link: 'Länk',
		link_modal_bookmark: 'Bokmärke',
		link_modal_downloadLinkCheck: 'Nedladdningslänk',
		link_modal_newWindowCheck: 'Öppna i nytt fönster',
		link_modal_text: 'Länktext',
		link_modal_title: 'Lägg till länk',
		link_modal_url: 'URL till länk',
		link_modal_relAttribute: 'Rel attribut',
		list: 'Listor',
		math: 'Math',
		math_modal_fontSizeLabel: 'Textstorlek',
		math_modal_inputLabel: 'Matematisk notation',
		math_modal_previewLabel: 'Preview',
		math_modal_title: 'Math',
		maxSize: 'Maxstorlek',
		mediaGallery: 'Rel attribut',
		mention: 'Namn',
		menu_bordered: 'Avgränsningslinje',
		menu_code: 'Kod',
		menu_neon: 'Neon',
		menu_shadow: 'Skugga',
		menu_spaced: 'Avstånd',
		menu_translucent: 'Genomskinlig',
		mergeCells: 'Sammanfoga celler (merge)',
		minSize: 'Minsta storlek',
		mirrorHorizontal: 'Spegling, horisontell',
		mirrorVertical: 'Spegling, vertikal',
		newDocument: 'Rel attribut',
		numberedList: 'Numrerad lista',
		outdent: 'Öka indrag',
		pageBreak: 'Sidbrytning',
		pageDown: 'Sidbrytning',
		pageNumber: 'Sidnummer',
		pageUp: 'Sida upp',
		paragraphStyle: 'Stil på stycke',
		preview: 'Preview',
		print: 'Print',
		proportion: 'Spara proportioner',
		ratio: 'Förhållande',
		redo: 'Gör om',
		remove: 'Ta bort',
		removeFormat: 'Ta bort formattering',
		replace: 'Ersätta',
		replaceAll: 'Byt ut alla',
		resize100: 'Förstora 100%',
		resize25: 'Förstora 25%',
		resize50: 'Förstora 50%',
		resize75: 'Förstora 75%',
		resize: 'Ändra storlek',
		revert: 'Återgå',
		revisionHistory: 'Revisionshistorik',
		right: 'Höger',
		rotateLeft: 'Rotera till vänster',
		rotateRight: 'Rotera till höger',
		row: 'Rad',
		save: 'Spara',
		search: 'Sök',
		selectAll: 'Välj Alla',
		showBlocks: 'Visa block',
		size: 'Storlek',
		splitCells: 'Separera celler',
		strike: 'Överstruket',
		submitButton: 'Skicka',
		subscript: 'Sänkt skrift',
		superscript: 'Höjd skrift',
		table: 'Tabell',
		tableHeader: 'Rubrik tabell',
		tableProperties: 'Tabellegenskaper',
		tags: 'Tags',
		tag_blockquote: 'Citer',
		tag_div: 'Normal (DIV)',
		tag_h: 'Rubrik',
		tag_p: 'Paragraf',
		tag_pre: 'Kod',
		template: 'Mall',
		textStyle: 'Textstil',
		title: 'Titel',
		underline: 'Understruket',
		undo: 'Ångra',
		unlink: 'Ta bort länk',
		verticalSplit: 'Separera vertikalt',
		video: 'Video',
		videoGallery: 'Videogalleri',
		video_modal_file: 'Lägg till från fil',
		video_modal_title: 'Lägg till video',
		video_modal_url: 'Bädda in video / YouTube,Vimeo',
		width: 'Bredd'
	};

	if (typeof noGlobal === typeof undefined) {
		if (!window.SUNEDITOR_LANG) {
			Object.defineProperty(window, 'SUNEDITOR_LANG', {
				enumerable: true,
				writable: false,
				configurable: false,
				value: {}
			});
		}

		Object.defineProperty(window.SUNEDITOR_LANG, 'se', {
			enumerable: true,
			writable: true,
			configurable: true,
			value: lang
		});
	}

	return lang;
});
