// Urdu
(function (global, factory) {
	if (typeof module === 'object' && typeof module.exports === 'object') {
		module.exports = global.document
			? factory(global, true)
			: function (w) {
					if (!w.document) {
						throw new Error('SUNEDITOR_LANG a window with a document');
					}
					return factory(w);
			  };
	} else {
		factory(global);
	}
})(typeof window !== 'undefined' ? window : this, function (window, noGlobal) {
	const lang = {
		code: 'ur',
		align: 'رخ',
		alignBottom: 'نیچے سیدھ کریں۔',
		alignCenter: 'مرکز میں طرف',
		alignJustify: 'ہر طرف برابر',
		alignLeft: 'بائیں طرف',
		alignMiddle: 'درمیان میں سیدھ کریں۔',
		alignRight: 'دائیں طرف',
		alignTop: 'اوپر سیدھ کریں۔',
		anchor: 'اینکر',
		asBlock: 'ایک بلاک کے طور پر',
		asInline: 'ان لائن کے طور پر',
		asLink: 'لنک کے طور پر',
		audio: 'آواز',
		audioGallery: 'آڈیو گیلری',
		audio_modal_file: 'فائلوں سے منتخب کریں',
		audio_modal_title: 'آواز داخل کریں',
		audio_modal_url: 'آواز URL',
		autoSize: 'ازخود حجم',
		backgroundColor: 'رنگ کو نمایاں کریں۔',
		basic: 'بنیادی',
		blockStyle: 'بلاک انداز',
		bold: 'بولڈ',
		border: 'بارڈر',
		border_all: 'سب کو بارڈر کریں۔',
		border_inside: 'اندر کی سرحد',
		border_horizontal: 'بارڈر افقی',
		border_vertical: 'عمودی بارڈر',
		border_outside: 'باہر کی سرحد',
		border_left: 'بارڈر چھوڑ دیا۔',
		border_top: 'بارڈر ٹاپ',
		border_right: 'بارڈر دائیں',
		border_bottom: 'بارڈر نیچے',
		border_none: 'بارڈر کوئی نہیں۔',
		bulletedList: 'غیر ترتیب شدہ فہرست',
		cancel: 'منسوخ کریں۔',
		caption: 'عنوان',
		cellProperties: 'سیل کی خصوصیات',
		center: 'مرکز',
		close: 'بند کریں',
		codeView: 'کوڈ کا نظارہ',
		color: 'رنگ',
		colorPicker: 'رنگ چننے والا',
		column: 'کالم',
		comment: 'تبصرے',
		commentAdd: 'تبصرہ شامل کریں۔',
		commentShow: 'تبصرے دکھائیں۔',
		copy: 'کاپی',
		copyFormat: 'پینٹ فارمیٹنگ',
		cut: 'کاٹنا',
		default: 'طے شدہ',
		deleteColumn: 'ستون حذف کریں',
		deleteRow: 'قطار کو حذف کریں',
		dir_ltr: 'بائیں سے دائیں',
		dir_rtl: 'دائیں سے بائیں',
		download: 'ڈاؤن لوڈ کریں۔',
		drag: 'گھسیٹیں۔',
		drawing: 'ڈرائنگ',
		drawing_modal_title: 'ڈرائنگ',
		edit: 'ترمیم',
		embed: 'ایمبیڈ',
		embed_modal_title: 'ایمبیڈ',
		embed_modal_source: 'ایمبیڈ ماخذ / URL',
		exportPDF: 'PDF میں برآمد کریں',
		exportWord: 'Word میں برآمد کریں',
		find: 'تلاش کریں۔',
		decrease: 'کمی',
		increase: 'اضافہ',
		fileBrowser: 'فائل براؤزر',
		fileGallery: 'فائل گیلری',
		fileUpload: 'فائل اپ لوڈ کریں۔',
		fixedColumnWidth: 'مقررہ ستون کی چوڑائی',
		font: 'فونٹ',
		fontColor: 'لکھائی کا رنگ',
		fontSize: 'سائز',
		formats: 'فارمیٹس',
		fullScreen: 'پوری اسکرین',
		height: 'اونچائی',
		horizontalLine: 'لکیر',
		horizontalSplit: 'افقی تقسیم',
		hr_dashed: 'ڈیشڈ',
		hr_dotted: 'نقطے دار',
		hr_solid: 'ٹھوس',
		id: 'ID',
		image: 'تصویر',
		imageGallery: 'تصویری نگارخانہ',
		image_modal_altText: 'متبادل متن',
		image_modal_file: 'فائلوں سے منتخب کریں',
		image_modal_title: 'تصویر داخل کریں',
		image_modal_url: 'تصویری URL',
		importWord: 'Word سے درآمد کریں',
		indent: 'حاشیہ',
		inlineStyle: 'ان لائن انداز',
		insertColumnAfter: 'اس کے بعد ستون شامل کریں',
		insertColumnBefore: 'پہلے ستون شامل کریں',
		insertRowAbove: 'اوپر قطار شامل کریں',
		insertRowBelow: 'نیچے قطار شامل کریں',
		insertLine: 'لائن داخل کریں۔',
		italic: 'ترچھا',
		layout: 'لے آؤٹ',
		left: 'بائیں',
		lineHeight: 'لکیر کی اونچائی',
		link: 'لنک',
		link_modal_bookmark: 'بک مارک',
		link_modal_downloadLinkCheck: 'ڈاؤن لوڈ لنک',
		link_modal_newWindowCheck: 'نئی ونڈو میں کھولیں',
		link_modal_text: 'ظاہر کرنے کے لیے متن',
		link_modal_title: 'لنک داخل کریں',
		link_modal_url: 'لنک کرنے کے لیے URL',
		link_modal_relAttribute: 'Rel وصف',
		list: 'فہرست',
		math: 'ریاضی',
		math_modal_fontSizeLabel: 'حرف کا سائز',
		math_modal_inputLabel: 'ریاضیاتی اشارے',
		math_modal_previewLabel: 'پیش نظارہ',
		math_modal_title: 'ریاضی',
		maxSize: 'زیادہ سے زیادہ سائز',
		mediaGallery: 'میڈیا گیلری',
		mention: 'تذکرہ',
		menu_bordered: 'سرحدی',
		menu_code: 'کوڈ',
		menu_neon: 'نیین',
		menu_shadow: 'سایہ',
		menu_spaced: 'فاصلہ',
		menu_translucent: 'پارباسی',
		mergeCells: 'حجروں کو ضم کریں',
		minSize: 'کم از کم سائز',
		mirrorHorizontal: 'آئینہ، افقی',
		mirrorVertical: 'آئینہ، عمودی',
		newDocument: 'نئی دستاویز',
		numberedList: 'ترتیب شدہ فہرست',
		outdent: 'ہاشیہ واپس',
		pageBreak: 'صفحہ توڑ',
		pageDown: 'صفحہ نیچے',
		pageNumber: 'صفحہ نمبر',
		pageUp: 'صفحہ اوپر',
		paragraphStyle: 'عبارت کا انداز',
		preview: 'پیشنظر',
		print: 'پرنٹ کریں',
		proportion: 'تناسب کو محدود کریں',
		ratio: 'تناسب',
		redo: 'دوبارہ کریں',
		remove: 'حذف',
		removeFormat: 'فارمیٹ کو حذف دیں',
		replace: 'بدل دیں۔',
		replaceAll: 'سب کو بدل دیں۔',
		resize100: '100% کا حجم تبدیل کریں',
		resize25: '25% کا حجم تبدیل کریں',
		resize50: '50% کا حجم تبدیل کریں',
		resize75: '75% کا حجم تبدیل کریں',
		resize: 'سائز تبدیل کریں۔',
		revert: 'واپس',
		revisionHistory: 'نظرثانی کی تاریخ',
		right: 'دائیں',
		rotateLeft: 'بائیں گھومو',
		rotateRight: 'دائیں گھمائیں',
		row: 'قطار',
		save: 'محفوظ کریں',
		search: 'تلاش کریں',
		selectAll: 'سبھی کو منتخب کریں۔',
		showBlocks: 'ڈبے دکھائیں',
		size: 'حجم',
		splitCells: 'حجروں کو علیدہ کرو',
		strike: 'لکیرہ کردہ',
		submitButton: 'بھیجیں',
		subscript: 'ذیلی',
		superscript: 'انتہائی',
		table: 'میز',
		tableHeader: 'میز کی سرخی',
		tableProperties: 'ٹیبل کی خصوصیات',
		tags: 'ٹیگز',
		tag_blockquote: 'اقتباس',
		tag_div: 'عام (div)',
		tag_h: 'ہیڈر',
		tag_p: 'پیراگراف',
		tag_pre: 'کوڈ',
		template: 'سانچہ',
		textStyle: 'متن کا انداز',
		title: 'عنوان',
		underline: 'انڈر لائن',
		undo: 'واپس کریں',
		unlink: 'لنک ختم کریں',
		VerticalSplit: 'عمودی تقسیم',
		video: 'ویڈیو',
		videoGallery: 'ویڈیو گیلری',
		video_modal_file: 'فائلوں سے منتخب کریں',
		video_modal_title: 'ویڈیو داخل کریں',
		video_modal_url: 'ذرائع ابلاغ کا یو آر ایل، یوٹیوب/ویمیو',
		width: 'چوڑائی'
	};

	if (typeof noGlobal === typeof undefined) {
		if (!window.SUNEDITOR_LANG) {
			Object.defineProperty(window, 'SUNEDITOR_LANG', {
				enumerable: true,
				writable: false,
				configurable: false,
				value: {}
			});
		}

		Object.defineProperty(window.SUNEDITOR_LANG, 'ua', {
			enumerable: true,
			writable: true,
			configurable: true,
			value: lang
		});
	}

	return lang;
});
