// Simplified Chinese, Mainland China
(function (global, factory) {
	if (typeof module === 'object' && typeof module.exports === 'object') {
		module.exports = global.document
			? factory(global, true)
			: function (w) {
					if (!w.document) {
						throw new Error('SUNEDITOR_LANG a window with a document');
					}
					return factory(w);
			  };
	} else {
		factory(global);
	}
})(typeof window !== 'undefined' ? window : this, function (window, noGlobal) {
	const lang = {
		code: 'zh_cn',
		align: '对齐方式',
		alignBottom: '底部对齐',
		alignCenter: '居中',
		alignJustify: '两端对齐',
		alignLeft: '左对齐',
		alignMiddle: '中间对齐',
		alignRight: '右对齐',
		alignTop: '顶部对齐',
		anchor: '锚点',
		asBlock: '作为块',
		asInline: '作为内联',
		asLink: '作为链接',
		audio: '音讯',
		audioGallery: '音频库',
		audio_modal_file: '上传图片',
		audio_modal_title: '插入音频',
		audio_modal_url: '音频网址',
		autoSize: '自动调整大小',
		backgroundColor: '背景颜色',
		basic: '基本',
		blockStyle: '块样式',
		bold: '粗体',
		border: '边框',
		border_all: '全部边框',
		border_inside: '内侧边框',
		border_horizontal: '水平边框',
		border_vertical: '垂直边框',
		border_outside: '外侧边框',
		border_left: '左侧边框',
		border_top: '顶部边框',
		border_right: '右侧边框',
		border_bottom: '底部边框',
		border_none: '无边框',
		bulletedList: '无序列表',
		cancel: '取消',
		caption: '标题',
		cellProperties: '单元格属性',
		center: '居中',
		close: '取消',
		codeView: '代码视图',
		color: '颜色',
		colorPicker: '颜色选择器',
		column: '列',
		comment: '评论',
		commentAdd: '添加评论',
		commentShow: '显示评论',
		copy: '复制',
		copyFormat: '绘画格式',
		cut: '剪切',
		default: '默认',
		deleteColumn: '删除列',
		deleteRow: '删除行',
		dir_ltr: '左到右',
		dir_rtl: '右到左',
		download: '下载',
		drag: '拖动',
		drawing: '绘图',
		drawing_modal_title: '绘图',
		edit: '编辑',
		embed: '嵌入',
		embed_modal_title: '嵌入',
		embed_modal_source: '嵌入源 / URL',
		exportPDF: '导出为 PDF',
		exportWord: '导出为 Word',
		find: '查找',
		decrease: '减少',
		increase: '增加',
		fileBrowser: '文件浏览器',
		fileGallery: '文件库',
		fileUpload: '文件上传',
		fixedColumnWidth: '固定列宽',
		font: '字体',
		fontColor: '字体颜色',
		fontSize: '字号',
		formats: '格式',
		fullScreen: '全屏',
		height: '高度',
		horizontalLine: '水平线',
		horizontalSplit: '水平分割',
		hr_dashed: '虚线',
		hr_dotted: '点线',
		hr_solid: '实线',
		id: 'ID',
		image: '图片',
		imageGallery: '图片库',
		image_modal_altText: '替换文字',
		image_modal_file: '上传图片',
		image_modal_title: '插入图片',
		image_modal_url: '图片网址',
		importWord: '从 Word 导入',
		indent: '增加缩进',
		inlineStyle: '内联样式',
		insertColumnAfter: '在右侧插入',
		insertColumnBefore: '在左侧插入',
		insertRowAbove: '在上方插入',
		insertRowBelow: '在下方插入',
		insertLine: '插入行',
		italic: '斜体',
		layout: '布局',
		left: '左',
		lineHeight: '行高',
		link: '超链接',
		link_modal_bookmark: '书签',
		link_modal_downloadLinkCheck: '下载链接',
		link_modal_newWindowCheck: '在新标签页中打开',
		link_modal_text: '要显示的文字',
		link_modal_title: '插入超链接',
		link_modal_url: '网址',
		link_modal_relAttribute: 'Rel 属性',
		list: '列表',
		math: '数学',
		math_modal_fontSizeLabel: '字号',
		math_modal_inputLabel: '数学符号',
		math_modal_previewLabel: '预览',
		math_modal_title: '数学',
		maxSize: '最大尺寸',
		mediaGallery: '媒体库',
		mention: '提到',
		menu_bordered: '边界线',
		menu_code: '代码',
		menu_neon: '霓虹灯',
		menu_shadow: '阴影',
		menu_spaced: '间隔开',
		menu_translucent: '半透明',
		mergeCells: '合并单元格',
		minSize: '最小尺寸',
		mirrorHorizontal: '翻转左右',
		mirrorVertical: '翻转上下',
		newDocument: '新文档',
		numberedList: '有序列表',
		outdent: '减少缩进',
		pageBreak: '分页符',
		pageDown: '向下翻页',
		pageNumber: '页码',
		pageUp: '向上翻页',
		paragraphStyle: '段落样式',
		preview: '预览',
		print: '打印',
		proportion: '比例',
		ratio: '比',
		redo: '恢复',
		remove: '删除',
		removeFormat: '清除格式',
		replace: '替换',
		replaceAll: '全部替换',
		resize100: '放大 100%',
		resize25: '放大 25%',
		resize50: '放大 50%',
		resize75: '放大 75%',
		resize: '调整大小',
		revert: '恢复',
		revisionHistory: '修订历史',
		right: '右',
		rotateLeft: '向左旋转',
		rotateRight: '向右旋转',
		row: '行',
		save: '保存',
		search: '搜索',
		selectAll: '全选',
		showBlocks: '显示块区域',
		size: '尺寸',
		splitCells: '分割单元格',
		strike: '删除线',
		submitButton: '确定',
		subscript: '下标',
		superscript: '上标',
		table: '表格',
		tableHeader: '表格标题',
		tableProperties: '表格属性',
		tags: '标签',
		tag_blockquote: '引用',
		tag_div: '正文 (DIV)',
		tag_h: '标题',
		tag_p: '段落',
		tag_pre: '代码',
		template: '模板',
		textStyle: '文字样式',
		title: '标题',
		underline: '下划线',
		undo: '撤消',
		unlink: '去除链接',
		verticalSplit: '垂直分割',
		video: '视频',
		videoGallery: '视频库',
		video_modal_file: '上传图片',
		video_modal_title: '插入视频',
		video_modal_url: '嵌入网址, Youtube,Vimeo',
		width: '宽度'
	};

	if (typeof noGlobal === typeof undefined) {
		if (!window.SUNEDITOR_LANG) {
			Object.defineProperty(window, 'SUNEDITOR_LANG', {
				enumerable: true,
				writable: false,
				configurable: false,
				value: {}
			});
		}

		Object.defineProperty(window.SUNEDITOR_LANG, 'zh_cn', {
			enumerable: true,
			writable: true,
			configurable: true,
			value: lang
		});
	}

	return lang;
});
