export const env: {
	_w: Window;
	_d: Document;
	NO_EVENT: symbol;
	ON_OVER_COMPONENT: symbol;
	getXMLHttpRequest: typeof import('./env').getXMLHttpRequest;
	getPageStyle: typeof import('./env').getPageStyle;
	getIncludePath: typeof import('./env').getIncludePath;
	isResizeObserverSupported: boolean;
	isClipboardSupported: boolean;
	isEdge: boolean;
	isBlink: boolean;
	isGecko: boolean;
	isChromium: boolean;
	isSafari: boolean;
	isOSX_IOS: boolean;
	isAndroid: boolean;
	isMobile: boolean;
	cmdIcon: string;
	shiftIcon: string;
	DPI: number;
	KATEX_WEBSITE: string;
	MATHJAX_WEBSITE: string;
};
export const unicode: {
	zeroWidthSpace: string;
	zeroWidthRegExp: RegExp;
	onlyZeroWidthRegExp: RegExp;
	escapeStringRegexp: typeof import('./unicode').escapeStringRegexp;
};
export const converter: {
	htmlToEntity: typeof import('./converter').htmlToEntity;
	entityToHTML: typeof import('./converter').entityToHTML;
	debounce: typeof import('./converter').debounce;
	syncMaps: typeof import('./converter').syncMaps;
	getValues: typeof import('./converter').getValues;
	camelToKebabCase: typeof import('./converter').camelToKebabCase;
	kebabToCamelCase: typeof import('./converter').kebabToCamelCase;
	toFontUnit: typeof import('./converter').toFontUnit;
	nodeListToArray: typeof import('./converter').nodeListToArray;
	swapKeyValue: typeof import('./converter').swapKeyValue;
	createElementWhitelist: typeof import('./converter').createElementWhitelist;
	createElementBlacklist: typeof import('./converter').createElementBlacklist;
	isHexColor: typeof import('./converter').isHexColor;
	rgb2hex: typeof import('./converter').rgb2hex;
	getWidthInPercentage: typeof import('./converter').getWidthInPercentage;
	textToAnchor: typeof import('./converter').textToAnchor;
	spanToStyleNode: typeof import('./converter').spanToStyleNode;
	addUrlQuery: typeof import('./converter').addUrlQuery;
	_setDefaultOptionStyle: typeof import('./converter')._setDefaultOptionStyle;
	_setIframeStyleLinks: typeof import('./converter')._setIframeStyleLinks;
	_setAutoHeightStyle: typeof import('./converter')._setAutoHeightStyle;
};
export const dom: {
	query: {
		getPositionIndex: typeof import('./dom/domQuery').getPositionIndex;
		getNodePath: typeof import('./dom/domQuery').getNodePath;
		getNodeFromPath: typeof import('./dom/domQuery').getNodeFromPath;
		getListChildren: typeof import('./dom/domQuery').getListChildren;
		getListChildNodes: typeof import('./dom/domQuery').getListChildNodes;
		getNodeDepth: typeof import('./dom/domQuery').getNodeDepth;
		sortNodeByDepth: typeof import('./dom/domQuery').sortNodeByDepth;
		compareElements: typeof import('./dom/domQuery').compareElements;
		getParentElement: typeof import('./dom/domQuery').getParentElement;
		getParentElements: typeof import('./dom/domQuery').getParentElements;
		getCommandTarget: typeof import('./dom/domQuery').getCommandTarget;
		getEventTarget: typeof import('./dom/domQuery').getEventTarget;
		getEdgeChild: typeof import('./dom/domQuery').getEdgeChild;
		getEdgeChildNodes: typeof import('./dom/domQuery').getEdgeChildNodes;
		getPreviousDeepestNode: typeof import('./dom/domQuery').getPreviousDeepestNode;
		getNextDeepestNode: typeof import('./dom/domQuery').getNextDeepestNode;
		findTextIndexOnLine: typeof import('./dom/domQuery').findTextIndexOnLine;
		findTabEndIndex: typeof import('./dom/domQuery').findTabEndIndex;
		getScrollParent: typeof import('./dom/domQuery').getScrollParent;
		getIframeDocument: typeof import('./dom/domQuery').getIframeDocument;
	};
	check: {
		isZeroWidth: typeof import('./dom/domCheck').isZeroWidth;
		isEdgePoint: typeof import('./dom/domCheck').isEdgePoint;
		isText: typeof import('./dom/domCheck').isText;
		isElement: typeof import('./dom/domCheck').isElement;
		isInputElement: typeof import('./dom/domCheck').isInputElement;
		isButtonElement: typeof import('./dom/domCheck').isButtonElement;
		isList: typeof import('./dom/domCheck').isList;
		isListCell: typeof import('./dom/domCheck').isListCell;
		isTable: typeof import('./dom/domCheck').isTable;
		isTableElements: typeof import('./dom/domCheck').isTableElements;
		isTableCell: typeof import('./dom/domCheck').isTableCell;
		isTableRow: typeof import('./dom/domCheck').isTableRow;
		isBreak: typeof import('./dom/domCheck').isBreak;
		isAnchor: typeof import('./dom/domCheck').isAnchor;
		isMedia: typeof import('./dom/domCheck').isMedia;
		isIFrame: typeof import('./dom/domCheck').isIFrame;
		isFigure: typeof import('./dom/domCheck').isFigure;
		isEmptyLine: typeof import('./dom/domCheck').isEmptyLine;
		isWysiwygFrame: typeof import('./dom/domCheck').isWysiwygFrame;
		isNonEditable: typeof import('./dom/domCheck').isNonEditable;
		isSpanWithoutAttr: typeof import('./dom/domCheck').isSpanWithoutAttr;
		isSameAttributes: typeof import('./dom/domCheck').isSameAttributes;
		isExcludeFormat: typeof import('./dom/domCheck').isExcludeFormat;
		isUneditable: typeof import('./dom/domCheck').isUneditable;
		isImportantDisabled: typeof import('./dom/domCheck').isImportantDisabled;
	};
	utils: {
		clone: typeof import('./dom/domUtils').clone;
		createElement: typeof import('./dom/domUtils').createElement;
		createTextNode: typeof import('./dom/domUtils').createTextNode;
		getAttributesToString: typeof import('./dom/domUtils').getAttributesToString;
		arrayFilter: typeof import('./dom/domUtils').arrayFilter;
		arrayFind: typeof import('./dom/domUtils').arrayFind;
		arrayIncludes: typeof import('./dom/domUtils').arrayIncludes;
		getArrayIndex: typeof import('./dom/domUtils').getArrayIndex;
		nextIndex: typeof import('./dom/domUtils').nextIndex;
		prevIndex: typeof import('./dom/domUtils').prevIndex;
		copyTagAttributes: typeof import('./dom/domUtils').copyTagAttributes;
		copyFormatAttributes: typeof import('./dom/domUtils').copyFormatAttributes;
		removeItem: typeof import('./dom/domUtils').removeItem;
		changeElement: typeof import('./dom/domUtils').changeElement;
		changeTxt: typeof import('./dom/domUtils').changeTxt;
		setStyle: typeof import('./dom/domUtils').setStyle;
		setDisabled: typeof import('./dom/domUtils').setDisabled;
		hasClass: typeof import('./dom/domUtils').hasClass;
		addClass: typeof import('./dom/domUtils').addClass;
		removeClass: typeof import('./dom/domUtils').removeClass;
		toggleClass: typeof import('./dom/domUtils').toggleClass;
		flashClass: typeof import('./dom/domUtils').flashClass;
		getClientSize: typeof import('./dom/domUtils').getClientSize;
		getViewportSize: typeof import('./dom/domUtils').getViewportSize;
		applyInlineStylesAll: typeof import('./dom/domUtils').applyInlineStylesAll;
		waitForMediaLoad: typeof import('./dom/domUtils').waitForMediaLoad;
		createTooltipInner: typeof import('./dom/domUtils').createTooltipInner;
	};
};
export const numbers: {
	is: typeof import('./numbers').is;
	get: typeof import('./numbers').get;
	getOverlapRangeAtIndex: typeof import('./numbers').getOverlapRangeAtIndex;
	isEven: typeof import('./numbers').isEven;
	isOdd: typeof import('./numbers').isOdd;
};
export const keyCodeMap: {
	isShift: typeof import('./keyCodeMap').isShift;
	isCtrl: typeof import('./keyCodeMap').isCtrl;
	isAlt: typeof import('./keyCodeMap').isAlt;
	isComposing: typeof import('./keyCodeMap').isComposing;
	isBackspace: typeof import('./keyCodeMap').isBackspace;
	isTab: typeof import('./keyCodeMap').isTab;
	isEnter: typeof import('./keyCodeMap').isEnter;
	isEsc: typeof import('./keyCodeMap').isEsc;
	isSpace: typeof import('./keyCodeMap').isSpace;
	isDirectionKey: typeof import('./keyCodeMap').isDirectionKey;
	isRemoveKey: typeof import('./keyCodeMap').isRemoveKey;
	isNonTextKey: typeof import('./keyCodeMap').isNonTextKey;
	isHistoryIgnoreKey: typeof import('./keyCodeMap').isHistoryIgnoreKey;
	isDocumentTypeObserverKey: typeof import('./keyCodeMap').isDocumentTypeObserverKey;
	isNonResponseKey: typeof import('./keyCodeMap').isNonResponseKey;
};
export const clipboard: {
	write: typeof import('./clipboard').write;
};
declare namespace _default {
	export { env };
	export { unicode };
	export { converter };
	export { dom };
	export { numbers };
	export { keyCodeMap };
	export { clipboard };
}
export default _default;
