const fs = require('fs');
const path = require('path');

/**
 * Format the main types/index.ts to have the desired structure:
 * - Custom header comment
 * - Re-export default exports as named exports
 * - interfaces namespace for TypeScript type access
 * - Main default export
 */

const indexPath = path.join(__dirname, '../../types/index.ts');

// Check if file exists
if (!fs.existsSync(indexPath)) {
	console.log('⚠️  format-index: index.ts not found, skipping...');
	process.exit(0);
}

// Define the modules to export
const modules = ['helper', 'langs', 'modules', 'plugins', 'interfaces'];

// Plugin types from plugin (class)
const pluginClasses = ['PluginBrowser', 'PluginCommand', 'PluginDropdown', 'PluginDropdownFree', 'PluginField', 'PluginInput', 'PluginModal', 'PluginPopup'];

// Generate the new content
const newContent = `/**
 * @file Automatically generated by "<Root>/scripts/ts-build/format-index.cjs"
 */

// Re-export default exports as named exports (값)
${modules.map((mod) => `export { default as ${mod} } from './${mod}';`).join('\n')}

// interfaces namespace (Plugin* classes only - Module* must be imported from "suneditor/interfaces")
import type _interfacesDefault from './interfaces';
export declare namespace interfaces {
${pluginClasses.map((t) => `\texport type ${t} = _interfacesDefault.${t};`).join('\n')}
}

// Main default export
export { default } from './suneditor';
`;

// Write the formatted content
fs.writeFileSync(indexPath, newContent, 'utf8');

console.log('✨ format-index: Formatted types/index.ts');
