/**
 * @warning "suneditor.js", "cdn-builder.js", "format-index.cjs" must be modified together.
 */

const fs = require('fs');
const path = require('path');

/**
 * Format the main types/index.ts to have the desired structure:
 * - Custom header comment
 * - Re-export from suneditor (which already exports helper, interfaces, langs, plugins, modules)
 * - interfaces namespace for TypeScript type access
 * - Main default export
 */

const indexPath = path.join(__dirname, '../../types/index.ts');

// Check if file exists
if (!fs.existsSync(indexPath)) {
	console.log('⚠️  format-index: index.ts not found, skipping...');
	process.exit(0);
}

// Modules with default export (have index with default)
const defaultExportModules = ['helper', 'langs', 'plugins'];

// Generate the new content
const newContent = `/**
 * @file Automatically generated by "<Root>/scripts/ts-build/format-index.cjs"
 */

// Re-export default exports as named exports
${defaultExportModules.map((mod) => `export { default as ${mod} } from './${mod}';`).join('\n')}

// Re-export modules (no default export in these)
import * as interfaces from './interfaces';
import * as moduleContract from './modules/contract';
import * as moduleManager from './modules/manager';
import * as moduleUI from './modules/ui';
export { interfaces };
export namespace modules {
\texport { moduleContract as contract };
\texport { moduleManager as manager };
\texport { moduleUI as ui };
}

// Main default export
export { default } from './suneditor';
`;

// Write the formatted content
fs.writeFileSync(indexPath, newContent, 'utf8');

console.log('✨ format-index: Formatted types/index.ts');
