name: Issue Management Action

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  manage-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run script to manage issues
        run: node .github/scripts/manage-issues.js
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
